### ISSUE TITLE
`baselayerchange` not being fired the first time a different layer is selected

### ISSUE THREAD

**Issue by tampeta** [vue-leaflet/Vue2Leaflet#172]
### Description
When the map first loads and I change to a different base layer, the `baselayerchange` event is not fired. I think this has something to do with the way `LControlLayers` component is implemented. 

From the leaflet documentation: 
> L.control.layers: "Creates an attribution control with the given layers. Base layers will be switched with radio buttons, while overlays will be switched with checkboxes. **Note that all base layers should be passed in the base layers object, but only one should be added to the map during map instantiation.**"

I think the base layers are all added in the map instantiation and results in the problem I have, which is also [described and explained here](https://gis.stackexchange.com/questions/259894/why-in-leaflet-does-baselayerchange-event-not-fire-until-the-second-time-the-bas/259909)

#### Steps to Reproduce
With more than one base layers on the map, click on any of the unselected base layers on the layers control.

#### Expected Results
`baselayerchange` event is fired on every change of radio button selection

#### Actual Results
`baselayerchange` event is only fired after the second time I select some radio button

### Versions
- Leaflet: v1.3.1
- Vue: v2.5.2
- Vue2Leaflet: v1.0.2

**Comment by KoRiGaN** [comment]
Hi @tampeta,

Thanks for raising this issue.
The live demo link you provide doesn't seem to be the right one.

From your description, I can say that this is probably a bug and a fix in Vue2Leaflet will be required to solve this.

Micka

**Comment by DonNicoJs** [comment]
We need to investigate if this bug is still present

**Comment by mishka251** [comment]
I am using leaflet-1.3.1 and django-leaflet and have this bug.
 I create a test sample, and take this bug in leaflet 1.5.1

Example here https://jsbin.com/furoqub/edit?html,js,output
That I expected: "base changed" in console every time, then base lauer changed.
That I have: Then I change layer from "Sputnik" to "OSM" with layer control i see nothing

**Comment by DonNicoJs** [comment]
@mishka251 Ehi this is vue2leaflet repository but apparently you are using vanilla leaflet! I suggest that you post this on the leaflet issue tracker :)
