### ISSUE TITLE
change LImageOverlay attribution

### ISSUE THREAD

**Issue by l02162010** [vue-leaflet/Vue2Leaflet#227]
How to change LImageOverlay attribution
I know LTileLayer can use like this to change attribution
 <l-tile-layer :url="url" :attribution="attribution"></l-tile-layer>

But, I don't know LImageOverlay how to do?

**Comment by lordfuoco** [comment]
@l02162010 Currently the attribution property on image overlay is not available, it will be included soon in a coming PR

**Comment by l02162010** [comment]
Have any way can change this?
like use
` L.control.attribution({
      prefix: false
    }).addAttribution('HQ @ Business Inc').addTo(this.$refs.map.mapObject);`
I can add addAttribution,but how to remove default tag

<img width="336" alt="2018-09-25 3 49 25" src="https://user-images.githubusercontent.com/14830189/46000286-afd25200-c0da-11e8-9f8f-5ac03eaf9c18.png">

**Comment by xiaosheng222** [comment]
I have the same question,
In the fine print, you can set it direct to `attribution: false` ([](https://leafletjs.com/reference-1.0.0.html#control-attribution)).
But setting `attribution: false` in the vue2-leaflet causes errors

![image](https://user-images.githubusercontent.com/19821241/46208007-de129480-c35b-11e8-864d-71e730b6b366.png)

**Comment by lordfuoco** [comment]
@xiaosheng222 you can set the attribution either to `null` or `''` or `undefined`

**Comment by xiaosheng222** [comment]
Yes, I finally set `' '`, I was worried that setting an `' '` might cause another problem, but I don't think it will cause another problem after looking at your answer.
Thank you very much indeed for your answer
