### ISSUE TITLE
How to stream point on map

### ISSUE THREAD

**Issue by moas** [vue-leaflet/Vue2Leaflet#311]
Hi
I load up a lot of points via API (with data pagination) and I want to stream them in the map. What is the best way to do this ?

thx.

**Comment by DonNicoJs** [comment]
@moas do you still have an issue with this? Sorry if I never got to answer you

**Comment by bezany** [comment]
Look like related #333 
If need show all points simplest way - show array of LMarkers.
Also can use `freezed` GeoJSON with points.
If there are a lot of points and you don’t always have to show everything I think may be helpful [vue2-leaflet-markercluster](https://github.com/jperelli/vue2-leaflet-markercluster).
