### ISSUE TITLE
Deep-Linking To Maker Popups

### ISSUE THREAD

**Issue by mikebronner** [vue-leaflet/Vue2Leaflet#417]
Not sure if this is the right place to ask: I am planning on deep-linking URLs to marker popups. Any suggestions on where to get started? Is there a tutorial on this? My goal is to be able to take a URL, and enter it in a browser that automatically opens the map with the marker popup already open.

Thanks for any suggestions! :)

**Comment by bezany** [comment]
@mikebronner  Hello! If I undestand You can programatically open popup with usage `mapObject` like this: `this.$refs.marker.mapObject.openPopup()`. Look example https://jsfiddle.net/bezanyu/ptmg5hy7/

**Comment by mikebronner** [comment]
@bezany Thanks for responding. I'm aware of that, however I need to incorporate it into vue-router to automatically open up based on the URL, and respond to browser actions (back- and forward-button clicks).

That means that each marker popup will respond to a unique URL, maybe something like `https://mysite.com/map/popup/22`

Do you have any suggestions on how do achieve that?

**Comment by bezany** [comment]
@mikebronner I think you can do something like this:
1. In you component create `props` with name `popupId`, type of `String`. And add watch on this property, when it is change, then open popup.
2. In you `router` options pass props to component from url. See [documentation](https://router.vuejs.org/guide/essentials/passing-props.html).
May be look like this:
`{ path: '/map/popup/:popupId', component: CustomPopup, props: true }`
