### ISSUE TITLE
leftlet plugin arc

### ISSUE THREAD

**Issue by chemoral87** [vue-leaflet/Vue2Leaflet#418]
How can I use the leaflet plugin to make arc or cuves, or someone needs to integrate.

https://github.com/mad-gooze/Leaflet.Arc

Help!!

**Comment by bezany** [comment]
@chemoral87 Use `mapObject` for get original [leaflet object](https://korigan.github.io/Vue2Leaflet/#/faq/?id=how-can-i-access-the-leaflet-map-object). See example https://jsfiddle.net/bezanyu/6y8g2m4L/
