### ISSUE TITLE
Pass custom property to the component

### ISSUE THREAD

**Issue by evgencode** [vue-leaflet/Vue2Leaflet#427]
### Description
There is a plugin that allows to add dragging capability to Leaflet path (Polygon, Polyline, Rectangle, Circle, CircleMarker…).
Path.Drag.js
If I want a path to be draggable as soon as it's added to map, I can add **draggable: true** to its options.
But this options are skiped whew I specify it into component.
Example:
```
<LCircle
  :lat-lng="[56.0, 43.0]"
  :radius="radius"
  :stroke="true"
  fill-color="#ff9900"
  :draggable="true"
/>
```

#### Expected Results
It would be good to be able to pass on additional parameters of third-party plug-ins to the components such as LCircle and so on.

#### Actual Results
optionsMerger skips parameters that do not belong to the circle instance.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.4.0
- Vue: v2.6.10
- Vue2Leaflet: v2.2.1

**Comment by DonNicoJs** [comment]
@evgencode if you don't need draggable to be reactive you can use the `options` prop to pass in any data you want.

Will this satisfy your use case?

**Comment by evgencode** [comment]
> @evgencode if you don't need draggable to be reactive you can use the `options` prop to pass in any data you want.
> 
> Will this satisfy your use case?

something like this?

 :options="{draggable: true}"

```
<LCircle
  :lat-lng="[56.0, 43.0]"
  :radius="radius"
  :stroke="true"
  fill-color="#ff9900"
  :options="{draggable: true}"
/>
```
Unfortunately, it doesn't help

**Comment by DonNicoJs** [comment]
@evgencode All our components extends the options mixin so they all have it. can you create a codesandbox repro  so I can take a deeper look ?

**Comment by evgencode** [comment]
> @evgencode All our components extends the options mixin so they all have it. can you create a codesandbox repro so I can take a deeper look ?

Here: https://codesandbox.io/embed/vue-template-irqyu

**Comment by DonNicoJs** [comment]
@evgencode  Options is imported component by component  :) as a mixin.
I will take a look at the repro case

**Comment by evgencode** [comment]
> @evgencode Options is imported component by component :) as a mixin.
> I will take a look at the repro case

"options" parameter works in all components except LCircle. Version 2.2.1

**Comment by DonNicoJs** [comment]
@evgencode you are 90% right, there is a couple more of component where options is missing! Nice catch I will provide a fix for this in the coming days! Thank you

**Comment by pumano** [comment]
@DonNicoJs any news about it? I found it really not working and `options` needed for setting all params in one place

**Comment by DonNicoJs** [comment]
@pumano Thanks for the ping, I have a release coming out today this will be included!

**Comment by evgencode** [comment]
Any fixes on this?

**Comment by pumano** [comment]
As seen in code - fixed. But I dont test it

**Comment by farhad321** [comment]
hello. i hame same this problem. please  fix :options @DonNicoJs
