### ISSUE TITLE
how to trigger click event on pressing enter key

### ISSUE THREAD

**Issue by webistomin** [vue-leaflet/Vue2Leaflet#432]
Hi! I can't trigger click event on marker on pressing enter key, mouse click works fine. I tried to do it in your documentation. I add the following code to your playgroud.  Am I missing something?

```vue
<template>
  <l-map style="height: 80%; width: 100%" :zoom="zoom" :center="center">
    <l-tile-layer :url="url"></l-tile-layer>
    <l-marker :lat-lng="markerLatLng" @click="test"></l-marker>
  </l-map>
</template>

<script>

Vue.component('l-map', Vue2Leaflet.LMap)
Vue.component('l-tile-layer', Vue2Leaflet.LTileLayer)
Vue.component('l-marker', Vue2Leaflet.LMarker)

export default {
  data () {
    return {
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      zoom: 3,
      center: [47.413220, -1.219482],
      markerLatLng: [47.313220, -1.319482]
    };
  },
  methods: {
    test() {
      alert(1);
    },
  },
}
</script>
```

#### Live Demo

https://korigan.github.io/Vue2Leaflet/#/components/l-marker/

#### Expected Results
run alert(1) by pressing enter key 

#### Actual Results
nothing happens

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge

**Comment by DonNicoJs** [comment]
Enter key is a different event! you need `@keypress.enter="test"` to trigger it

**Comment by webistomin** [comment]
@DonNicoJs still doesn't work :disappointed:

**Comment by Carnid** [comment]
@webistomin I suppose you want the keypress to work no matter what element is selected on your page. the `@keypress.enter` event is binded to the element you assigned it to, so it will only work when this element is selected.
In order to listen to the key press event for your entire page, you need to add an eventListener to your window. You may do it this way:
```
<template>
  <l-map style="height: 80%; width: 100%" :zoom="zoom" :center="center">
    <l-tile-layer :url="url"></l-tile-layer>
    <l-marker :lat-lng="markerLatLng" @click="test"></l-marker>
  </l-map>
</template>

<script>

Vue.component('l-map', Vue2Leaflet.LMap)
Vue.component('l-tile-layer', Vue2Leaflet.LTileLayer)
Vue.component('l-marker', Vue2Leaflet.LMarker)

export default {
  data () {
    return {
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      zoom: 3,
      center: [47.413220, -1.219482],
      markerLatLng: [47.313220, -1.319482]
    };
  },
  methods: {
    handleKeyDown(e) { //method to handle the keypress
      if (e.code === 'Enter') {
        this.test();
      }
    },
    test() {
      alert(1);
    },
  },
  created() {
    window.addEventListener('keydown', this.handleKeyDown); //will attach the event listener to the whole window when the component is created
  },
  destroyed() {
    window.removeEventListener('keydown', this.handleKeyDown); //will detach the event listener once the component is destroyed
  }
}
</script>
```

**Comment by webistomin** [comment]
> @webistomin I suppose you want the keypress to work no matter what element is selected on your page. the `@keypress.enter` event is binded to the element you assigned it to, so it will only work when this element is selected.
> In order to listen to the key press event for your entire page, you need to add an eventListener to your window. You may do it this way:
> 
> ```
> <template>
>   <l-map style="height: 80%; width: 100%" :zoom="zoom" :center="center">
>     <l-tile-layer :url="url"></l-tile-layer>
>     <l-marker :lat-lng="markerLatLng" @click="test"></l-marker>
>   </l-map>
> </template>
> 
> <script>
> 
> Vue.component('l-map', Vue2Leaflet.LMap)
> Vue.component('l-tile-layer', Vue2Leaflet.LTileLayer)
> Vue.component('l-marker', Vue2Leaflet.LMarker)
> 
> export default {
>   data () {
>     return {
>       url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
>       zoom: 3,
>       center: [47.413220, -1.219482],
>       markerLatLng: [47.313220, -1.319482]
>     };
>   },
>   methods: {
>     handleKeyDown(e) { //method to handle the keypress
>       if (e.code === 'Enter') {
>         this.test();
>       }
>     },
>     test() {
>       alert(1);
>     },
>   },
>   created() {
>     window.addEventListener('keydown', this.handleKeyDown); //will attach the event listener to the whole window when the component is created
>   },
>   destroyed() {
>     window.removeEventListener('keydown', this.handleKeyDown); //will detach the event listener once the component is destroyed
>   }
> }
> </script>
> ```

I am trying to do a11y marker. I want to select marker with **tab**, then hit **enter** and my logic for marker should work.

**Comment by Carnid** [comment]
@webistomin It will not work as you think it should, as the click event is binded to the marker element. For your browser, that means it will only trigger when marker element is actually currently in focus. If you want your code to work as is, you need to find a way to focus the marker element. If not, you need to add a keydown event on your entire window.

**Comment by webistomin** [comment]
> @webistomin It will not work as you think it should, as the click event is binded to the marker element. For your browser, that means it will only trigger when marker element is actually currently in focus. If you want your code to work as is, you need to find a way to focus the marker element. If not, you need to add a keydown event on your entire window.

Thanks! I tried to it on [original leafler map](https://leafletjs.com/) and it works fine. So I assume that I can do the same thing here.
