### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by chemoral87** [vue-leaflet/Vue2Leaflet#435]
I would like to use cache title layer, to render faster, more than 600 polygons in android web broser.

https://codepen.io/re5pawn/pen/YNjjQy

**Comment by hubertokf** [comment]
I'm with this quest. Have you tried 
[http://mazemap.github.io/Leaflet.TileLayer.PouchDBCached/](http://mazemap.github.io/Leaflet.TileLayer.PouchDBCached/) and passing to LTileLayer
options: {useCache:true} 

Now I want to seed only what i want using seed function, but i couldnt do it
