### ISSUE TITLE
Feature: Dynamic options

### ISSUE THREAD

**Issue by yaki4** [vue-leaflet/Vue2Leaflet#439]
First of all, thanks for this great and really useful package.
Actually if my options depend on a dynamic variables my map will not be updated. 
But i can change it with this.$refs.map.mapObject.myOption.enabled();

It would be great if options are dynamic.

JsFiddle of exemple: https://jsfiddle.net/hdboL9pz/2/

**Comment by DonNicoJs** [comment]
@yaki4 Hi! this is very tricky because leaflet iteslf do not support all the 'setMyOption' that we use to make them 'dynamic' 

What is the prop/s that you are trying to pass in options and that need to change?

**Comment by yaki4** [comment]
Oh i understand,
currently it was for zoomControl and scrollWheelZoom.

Thanks for your response.

**Comment by DonNicoJs** [comment]
@yaki4 so yeah those two options do not have a leaflet setter. Changing them would mean redraw the map and we feel that is not okay to do so by reacting on a dynamic prop.

What is your precise use caee?
