### ISSUE TITLE
Zoom on CMD plus / minus hotkeys

### ISSUE THREAD

**Issue by webcoderkz** [vue-leaflet/Vue2Leaflet#445]
Right now, i can zoom with just a mouse scroll up /down, or a trackpad zoom in / out, is it possible prevent this even and rebind it to CMD / WIN / Super + zoom in / out hotkey?

**Comment by DonNicoJs** [comment]
@webcoderkz Yes this is possible, please check the leaflet documentation on how to achieve this!
