### ISSUE TITLE
Permanent tooltips are not reactive

### ISSUE THREAD

**Issue by yohannlegrand** [vue-leaflet/Vue2Leaflet#446]
### Description
Tooltips set with 'permanent' option aren't reactive.
In my application, the refresh of my data doesn't update the tooltips when they are set with 'permanent: true'.
For example, I try to update the option object when data.isActive is updated (I use Vuex for reactivity and I loop through my data to show the tooltips)
But Leaflet doesn't update the tooltip.

### Versions
- Leaflet: v1.5.1
- Vue: v2.6.10
- Vue2Leaflet: v2.2.1

**Comment by DonNicoJs** [comment]
@yohannlegrand Sorry for the very slow reply, I will investigate this

**Comment by ivopisarovic** [comment]
Confirming this bug.

**Comment by bkarlson** [comment]
Confirming too: updating marker coordinates from Vue moves marker, but not tooltip. When dragging marker with mouse/tap, everything's fine.

**Comment by darivs** [comment]
Are there any news on this topic @DonNicoJs ? It would be very handy if the tooltip options could be updated reactively

**Comment by ryanmoore-SM** [comment]
Discovered this today as well. Didn't realize it was because of the permanent option til I found this post.

**Comment by kuromoka** [comment]
I submitted PR #718

**Comment by KoRiGaN** [comment]
PR from @kuromoka is now merged
