### ISSUE TITLE
leaflet setup not working with electron-vue app

### ISSUE THREAD

**Issue by dhall2211** [vue-leaflet/Vue2Leaflet#451]
having issues rendering the leaflet map on an electron-vue build enviroment. When I run the app I get a error in the main.js file where it cant resolve the path of the iconRetinaURl, iconURL, and shawdowURL properties.  below is my code and the error message. any help would be great thanks!

 ERROR in ./src/renderer/main.js
  Module not found: Error: Can't resolve '/leaflet/dist/images/marker-icon-2x.png' in 'C:\Users\dh\Documents\Projects\braumann-map\src\renderer'
   @ ./src/renderer/main.js 13:17-67
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  ERROR in ./src/renderer/main.js
  Module not found: Error: Can't resolve '/leaflet/dist/images/marker-icon.png' in 'C:\Users\dh\Documents\Projects\braumann-map\src\renderer'
   @ ./src/renderer/main.js 14:11-58
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  ERROR in ./src/renderer/main.js
  Module not found: Error: Can't resolve '/leaflet/dist/images/marker-shadow.png' in 'C:\Users\dh\Documents\Projects\braumann-map\src\renderer'
   @ ./src/renderer/main.js 15:13-62
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  ERROR in ./src/renderer/main.js
  Module not found: Error: Can't resolve 'leaflet' in 'C:\Users\dh\Documents\Projects\braumann-map\src\renderer'
   @ ./src/renderer/main.js 1:0-31 10:7-11 12:0-4
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

  ERROR in ./src/renderer/main.js
  Module not found: Error: Can't resolve 'leaflet/dist/leaflet.css' in 'C:\Users\dh\Documents\Projects\braumann-map\src\renderer'
   @ ./src/renderer/main.js 5:0-34
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

`
import { Icon } from 'leaflet';
import Vue from 'vue';
import axios from 'axios';
/* eslint-disable */
import 'leaflet/dist/leaflet.css';
import App from './App';
import router from './router';
import store from './store';

// this part resolve an issue where the markers would not appear
delete Icon.Default.prototype._getIconUrl;

Icon.Default.mergeOptions({
  iconRetinaUrl: require('/leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('/leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('/leaflet/dist/images/marker-shadow.png')
});

/* eslint-enable */

if (!process.env.IS_WEB) Vue.use(require('vue-electron'));
Vue.http = Vue.prototype.$http = axios;
Vue.config.productionTip = false;

/* eslint-disable no-new */
new Vue({
  components: { App },
  router,
  store,
  template: '<App/>',
}).$mount('#app');
`

**Comment by DonNicoJs** [comment]
@dhall2211 Could you also post your package.json? and please put it in `` so that it gets formatted :)
