### ISSUE TITLE
Zoom : how to get the 4 coordinates of the zoomed map?

### ISSUE THREAD

**Issue by mawieutc** [vue-leaflet/Vue2Leaflet#453]
Hello,

I am using vue2leaflet like this:

![image](https://user-images.githubusercontent.com/3974608/68281454-f3d2ad00-0077-11ea-80fe-3293662824a7.png)

When a filter is set by a user, a sql request is run and we get the new markers and results. for now, i am adding 50 results for each request, but we have thousands of them.

I would like to be able to zoom and to get results for this zone, such as airbnb does. **Is it possible to get the coordinates of the 4 points (top left, top right, bottom left, bottom right) of the map when zooming in?**
Is it how you would recommend doing it? getting these 4 points and sending the sql request to get the points which are in this zone?

Thanks a lot!

(The search results are the same as the markers, and when adding more than 100 results, it gets a bit slow.. cause I have images for each of them. but this is more of a detail)

**Comment by DonNicoJs** [comment]
@mawieutc This is an interesting request :) what you are interested is called `bounds`
you can check the example here:

https://korigan.github.io/Vue2Leaflet/#/components/l-map/

Note that bounds do support `sync` modifier

Let me know if this helps you!
