### ISSUE TITLE
Vue 3 Plan

### ISSUE THREAD

**Issue by DonNicoJs** [vue-leaflet/Vue2Leaflet#455]
Hi everyone, this issue is going to be the entry point for the discussion on what to do about vue3.

Due to the name of the repo ( which I can't change since I am not the owner ) I foresee some user confusion.

Also I would like to integrate the code with some ci/cd tools and bots to make my life more easy, but I can't since I have no access to the settings...

I see two options moving forward:

- fork, rename move from there
- keep working here, accept that the users are going to be confused.

If a fork is done, due to limited time I am going to drop support of this repo and keep offering security updates / bug fixes on the new codebase.

Everyone is free to comment here but I am tagging the people who committed the most.

@bezany @HIMISOCOOL @mikeu @javiertury @jericopulvera @jperelli

**Comment by mikeu** [comment]
Even if you did have access to change the name of the repo, there are some good arguments not to do that. In particular, it would have the potential to break any code out there that happened to reference the URL directly, as well as any blog posts people have written that point to it, etc.

I think my vote would be to fork the project and rename it (probably to something that _doesn't_ reference the version number of Vue in its name...). It seems as if that would provide many benefits to both the repo and your time @DonNicoJs , without many drawbacks other than a lack of updates to this repo.

Would you still be willing to provide minimal support here in terms of merging security fixes and publishing new versions to npm, if others provided any actual updates to the code that might be required?

**Comment by DonNicoJs** [comment]
> Even if you did have access to change the name of the repo, there are some good arguments not to do that. In particular, it would have the potential to break any code out there that happened to reference the URL directly, as well as any blog posts people have written that point to it, etc.
> 
> I think my vote would be to fork the project and rename it (probably to something that _doesn't_ reference the version number of Vue in its name...). It seems as if that would provide many benefits to both the repo and your time @DonNicoJs , without many drawbacks other than a lack of updates to this repo.
> 
> Would you still be willing to provide minimal support here in terms of merging security fixes and publishing new versions to npm, if others provided any actual updates to the code that might be required?

@mikeu I am thinking that if we go for a new repo I could fork this, and so always keep a vue2 branch that I can use to merge back security fixes and such.
Yes I am willing to maintain the npm package, especially for bug fixes and security fixes but not for new features which I would like to deal with in setup where I have CI/CD

**Comment by DonNicoJs** [comment]
Maybe @KoRiGaN wants to participate in this, my bad not to tag him

**Comment by pumano** [comment]
As a user (depend on this project), I prefer fork with CI/CD with just `vue-leaflet` repo name without version.

**Comment by DonNicoJs** [comment]
One drawback is that I would not be able to release vue-leaflet or even leaflet-vue npm packages since they are both taken, maybe I could scope it, anyone has an idea?

**Comment by pumano** [comment]
@DonNicoJs can @KoRiGaN provide you access more rights to this repo or move repo to organisation aka vue-leaflet/vue-leaflet? After it you can use it for CI/CD?

**Comment by DonNicoJs** [comment]
@pumano I think I am already on the 'highest' access before he needs to transfer the repo to me, which I guess ( and he has all the right for ) he does not want to, since I asked :)

**Comment by mikeu** [comment]
@pumano I'm not sure that there is any advantage to moving this repo, over forking it to a new location and continuing from there, is there? I do like the idea of creating it in an organisation though. And vue-leaflet/vue-leaflet is certainly a good starting point for the discussion, I think.

@DonNicoJs would vue-leaflet/vue-leaflet also work for npm, as @vue-leaflet/vue-leaflet? Or is that too similar to the existing package names, do you think? It would also give the opportunity to release some plugins under the @vue-leaflet namespace, perhaps, e.g. @vue-leaflet/polyline-measure (though I'm not sure what would be involved in allowing that to happen when the plugins are maintained by others).

**Comment by pumano** [comment]
@vue-leaflet/vue-leaflet for npm & vue-leaflet/vue-leaflet as github organisation sounds as win-win here.

**Comment by DonNicoJs** [comment]
I think I am going along and blocking the organisation name :) Even if we do not end up pursuing that road

**Comment by HIMISOCOOL** [comment]
very much interested in working on a vue 3 version.
looks like we have a winning strategy so far

**Comment by jperelli** [comment]
omg, plugins are also named vue2leaflet-something, what a bad choice we made earlier! lol.

I think I'm going to rename plugins to whatever you decide here. And will leave the old and new packages in npm just in case. And leave some notice in the README.md

As per this change here, the ideas I've read so far sound good, just leave a big notice in the README of this repo with a link pointing to the new fork if that's the case.

I don't know if you can somehow give some notice to users trying to get last version in npm on package.json, when installing, so that they change the name to the new repo

**Comment by DonNicoJs** [comment]
@jperelli as a plugin author would you be open to move the plugins in the vue-leaflet organisation? So they are all under the same scope?

**Comment by jperelli** [comment]
@DonNicoJs sounds good

**Comment by KoRiGaN** [comment]
My guess would be that an organisation is the way to go with a more generic name. I'm happy to create an open source org and transfer the repo over. 
However there is already an organisation called [vue-leafet](https://github.com/vue-leaflet) in github...

**Comment by pumano** [comment]
@KoRiGaN looks like it created by @DonNicoJs

**Comment by DonNicoJs** [comment]
@KoRiGaN I just added you as owner of the organisation :) if you want to transfer the repo that would actually be the best solution

**Comment by KoRiGaN** [comment]
Repo is transferred now

**Comment by DonNicoJs** [comment]
@KoRiGaN Thanks! @jperelli I've sent you an invitation for the organisation let me know if it arrived correctly

**Comment by ajmas** [comment]
Just one question: should we be keeping project names all lower case?

For example: https://github.com/vue-leaflet/vue2-leaflet as opposed to https://github.com/vue-leaflet/Vue2Leaflet ?

**Comment by DonNicoJs** [comment]
@ajmas Yep we will, I plan to create a new repo for the vue3 version called `vue-leaflet`

**Comment by INRIX-Jonny-Sooter** [comment]
Always though the repo name actually was Vue"to"leaflet, and had nothing related to the version of Vue

**Comment by DonNicoJs** [comment]
So since this issue is filled with people who contributed/contribute a lot this is a good start: 
https://discord.gg/aFR7pF


I've made a discord server to chat about vue-leaflet, and also kickstarted the vue3 repo with a tiny but working implementation:
https://github.com/vue-leaflet/vue-leaflet

**Comment by DonNicoJs** [comment]
@bezany @mikeu @pumano @jperelli  @KoRiGaN  https://github.com/vue-leaflet/vue-leaflet especially you guys

**Comment by mikeu** [comment]
@DonNicoJs discord is telling me that the invitation code is invalid or expired...

**Comment by DonNicoJs** [comment]
@mikeu ops!

https://discord.gg/uVZAfUf

This should be set to never expire

**Comment by DonNicoJs** [comment]
Closing this issue since have a v3 version
