### ISSUE TITLE
Map not react for set geojson layer's data

### ISSUE THREAD

**Issue by morfair** [vue-leaflet/Vue2Leaflet#475]
I have template:
```
<l-map>
    <l-geo-json :geojson="vehicles.geojson"></l-geo-json>
</l-map>
```
In <script> section I have class for my GeoJSON layer:

```
class GeoJSONLayer {
    constructor() {
        this.geojson = null;
    }
}
```

Below in **data() {}** I init my object:
```
vehicles: new GeoJSONLayer()
```
In **created() {}** axios's function:
```
API.getVehicles().then(
    res => {
        this.vehicles.geojson = res.data[0].vehicle_positions_geojson
        console.log(this.vehicles.geojson);
    },
    err => console.error(err)
)
```

In console I see logged right GeoJSON data, but no markers in map!!!
Help, please!

**Comment by DonNicoJs** [comment]
@morfair Why use a class? Like this vue reactivity is skipped, vue has no idea that the geoJson is modified, you can use `Vue.set` if you really need a class https://vuejs.org/v2/api/#Vue-set

**Comment by morfair** [comment]
@DonNicoJs I have multiple geojson layers, and I do not want code duplication =)

**Comment by morfair** [comment]
SORRY!!
I forgot say, that above examle is WORK, while I do not wrap GeoJSON layer in MarkerCluster:
```
<v-marker-cluster>
    <l-geo-json :geojson="vehicles.geojson"></l-geo-json>
</v-marker-cluster>
```

**Comment by DonNicoJs** [comment]
@morfair a geo-json should not be in a maker-cluster :) you can use a feature-group!

**Comment by ray007** [comment]
I have a `geojson` in a markercluster, and it works fine as long as I set the data only once.
Changing the `geojson` data structure unfortunately does not work.

**Comment by DonNicoJs** [comment]
@ray007 this is because as I mentioned I do not think `vue2leaflet markercluster` supports geojson properly. I do not think we have any way to detect that the geojson data is changed and thus redraw the cluster.

You can toggle `l-geo-json` and or `l-marker-cluster` with a `v-if` to force a redraw
