### ISSUE TITLE
Load .kmz file

### ISSUE THREAD

**Issue by zeeuss** [vue-leaflet/Vue2Leaflet#477]
Hi,

Please tell me how can I load .kmz files?

Thank you!

**Comment by DonNicoJs** [comment]
Hi @zeeuss Can you tell us what kind of approach are you taking? A piece of code? like this is very hard to help you

**Comment by zeeuss** [comment]
Thanks @DonNicoJs for answer!
I have some .kmz files and I must to display the data from them on the map. I found a library that works for leaflet: https://github.com/Raruto/leaflet-kmz. 
You can guide me to use this library in vue2-leaflet?

**Comment by DonNicoJs** [comment]
@zeeuss You can follow that plugin quick start guide, and simply do not use the 'js' constructors bu the vue components, to append the control you just need to grab it with a ref.

Try to give it a shot, and if not able I will try to help more
