### ISSUE TITLE
Incorrect visualization of Geojson using Vue2Leaflet

### ISSUE THREAD

**Issue by Munyvorn** [vue-leaflet/Vue2Leaflet#478]
Hello guys! I'm having a problem when visualizing my geojson files on the web using vue2leaflet. 
It is supposed to show. 
The user upload files in the form of .dxf, then the django backend process it into various layers and send it back to frontend. I received all the layers in the form of geojson object, and I use l-map of vue2leaflet to visualize whichever layer is selected
![image](https://user-images.githubusercontent.com/40157826/69692893-118ab380-1106-11ea-8cf1-5db206734ef8.png)

Could you please tell me what's happening here? The same code works perfectly with the example API given by the developer themselves, but not with my geojson, as the following: 

![image](https://user-images.githubusercontent.com/40157826/69692969-56164f00-1106-11ea-8d4b-c419ad3e9d58.png)

Note: my geojson if visualized in QGIS shows a map shape, or at least not such a straight line for the layer. 
Thank you in advance!

**Comment by DonNicoJs** [comment]
Hi @Munyvorn Can we see a piece of code? A js-fiddle / codesandbox would be the best :)

**Comment by Munyvorn** [comment]
Yes @DonNicoJs.
Here is the piece of code for visualizing the geojson of which the layer is selected.
> https://jsfiddle.net/#&togetherjs=aRi72c0h8k

or the screenshot:
![image](https://user-images.githubusercontent.com/40157826/69799194-6103d900-1205-11ea-96f1-482604865f1f.png)


The backend reads the dxf file, converts it into multiple layers; each one is a geojson file, then return all the geojson files for each layer back. I read and store it in the variable paths, and whenever a layer is elected through v:on change, I call setLayer function to assign the selected geojson to be visualized on the website.

**Comment by DonNicoJs** [comment]
I don't see any error in the vue2-leaflet implementation! Are you sure that you are assigning the correct property to geoJson ? 

What does it contain ( the console.log ) ?

**Comment by Munyvorn** [comment]
@DonNicoJs  Here is what the log looks like:
![image](https://user-images.githubusercontent.com/40157826/69901759-75d49e00-13b8-11ea-9ef5-dc97dba88469.png)

![image](https://user-images.githubusercontent.com/40157826/69901765-8be25e80-13b8-11ea-8136-da02a3e7e995.png)

The geojson object has the exact same format as the one that is used in your example when get through axios:
> https://github.com/vue-leaflet/Vue2Leaflet/blob/master/examples/src/components/GeoJSON.vue

**Comment by Munyvorn** [comment]
Sir @DonNicoJs, if you could simply provide me any sort of working code to visualize pure geojson, different from mine, that would be really helpful in my project. I am really struck with this visualization part in my project and the deadline is already over.

**Comment by DonNicoJs** [comment]
@Munyvorn Looking at screenshot is very hard to spot any mistakes, it seems all fine. To help you further I would need to access the system, is this a public work?

**Comment by Munyvorn** [comment]
> @Munyvorn Looking at screenshot is very hard to spot any mistakes, it seems all fine. To help you further I would need to access the system, is this a public work?

@DonNicoJs  here is my entire working vuejs code, based on the example given by you. But instead of using axios to read api data, I directly copy and paste the geojson data to the variable. This code shows the exact output with the one I am working on. I'm so sorry that I cannot reveal the current project I'm working on as it's confidential. 
> https://github.com/Munyvorn/GeojsonError

**Comment by Munyvorn** [comment]
@Anyone please kindly help me with this problem. That would mean a lot to me. I'm stuck with this part for so long and couldn't find alternative solutions.

**Comment by DonNicoJs** [comment]
@Munyvorn the problem is in the geojson, http://geojson.io/ try it here, I checked your code and beside the fact that you should not put a big object like a geojson in the data attribute there is nothing wrong.

Anyhow that geojson is invalid
