### ISSUE TITLE
Website (that includes examples) is not active 

### ISSUE THREAD

**Issue by nozkok** [vue-leaflet/Vue2Leaflet#479]
https://korigan.github.io/Vue2Leaflet/

this was working yesterday but today gives 404 error  :/

![image](https://user-images.githubusercontent.com/6912824/69787232-19f9f180-11cd-11ea-9f38-21b0994998f5.png)

**Comment by DonNicoJs** [comment]
@nozkok We are in the process of moving the repo, the website will be back online soo, in the meantime you can access the docs from the github repo

**Comment by DonNicoJs** [comment]
@nozkok Website is accessible again, the new url is: https://vue-leaflet.github.io/Vue2Leaflet/#/
The readme and project description is updated too
