### ISSUE TITLE
@click event not working inside l-icon

### ISSUE THREAD

**Issue by bestmazzo** [vue-leaflet/Vue2Leaflet#480]
### Description

I've been trying to make a custom marker icon which reacts to mouse events (basically triggers a function call on click). Unfortunately this doesn't seem to work
#### Live Demo

https://jsfiddle.net/nvcqw7d2/2/
#### Steps to Reproduce
Open above JSFiddle

#### Expected Results

Clicking on a element in the red box should open a alert
#### Actual Results

Nothing happens
### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.5.0
- Vue: v2.15.6
- Vue2Leaflet: v2.2.1

**Comment by disarticulate** [comment]
Here's a (almost working) hack:
https://jsfiddle.net/cveyLuto/3/

``` Vue Template
    <l-map :zoom="zoom" :center="center">
      <l-tile-layer :url="url" :attribution="attribution"></l-tile-layer>
      <l-marker :lat-lng="marker" @click="iconClick" ref="marker">
        <l-icon ref="icon">
          <div class="mydiv">
            <span @click="sayHello('hello')" class="myspan">
              HELLO</span><br />
            <span @click="sayHello('goodbye')" class="myspan">
              Goodbye</span>
          </div>
        </l-icon>
      </l-marker>
    </l-map>
```

```Methods
  methods: {
    // recurse through all the child element nodes and run the callback fn
    recurseNodes (element, fn) { 
      for (let el of element.childNodes) {
        this.recurseNodes(el, fn)
        fn(el)
      }
    },
    //recurse through all the vue component nodes and ruyn the callback fn
    recurseChildren (component, fn) {
      if (Array.isArray(component)) {
        component.map(child => this.recurseChildren(child, fn))
      }
      if (
        component &&
        component.$children &&
        component.$children.length > 0
      ) {
        component.$children.map(child => this.recurseChildren(child, fn))
      }
      fn(component)
    },
    iconClick (e) {
      // master click event on the l-marker (which swallows the child events?)
      let parentComponent = this.$refs.marker
      // the element of the marker 
      let parentNode = parentComponent.$el
      // the actual clicked element to find
      let childNode = e.originalEvent.target
      // search through all components
      this.recurseChildren(parentComponent, (component) => {
        if (component.click) { //if the component has a click (or whatever you want)
          // search through it's element nodes
          this.recurseNodes(component.$el, (el) => {
            // if this component has a node equal to the childNode from the event
            if (el.isEqualNode(childNode)) {
              // click on it (passing the originalEvent for good measure/as needed.
              component.click(e.originalEvent)
            }
          })
        }
      })
    	alert('hello')
    },
    sayHello(greet) {
      alert(greet)
    }
  }
```
This worked for me because the component I'm looking for has a .click handler in it.

However, I tried to reproduce it in the link you provided, but I can't find how that click function is being bound to the vue instance, thus I can't detect the click properly.

**Comment by DonNicoJs** [comment]
I did not have time to investigate this yet, but what about shifting your approach? Bind the click to the marker ( which works correctly ) and on the event you can go and verify what 'custom icon' you are using ( since is something that is or you calculated in the vue component / instance ) ?

**Comment by Zhang-DaLei** [comment]
I also encountered the same problem. I can't execute the click event of the custom icon. Is there a solution?

**Comment by disarticulate** [comment]
I am using random custom components being passed in from a framework,
quasar-framework.  But I would expect, as the OP test case shows, for basic
arbitrary code to work via template.

**Comment by DonNicoJs** [comment]
So as it is now this is what happening 
- we (vue-leaflet) create a marker
- we create an icon
- we take the generated markup for the icon and pass it to a leaflet function to populate the icon

Bindings, events they are all broken in the last step, because we are passing markup to a function. I would argue that LIcon is not the right place do event binding, which should all be delegated to the markers.

Happy to explore this more but there is no easy / not-hacky road ahead

**Comment by bestmazzo** [comment]
Thannk you, @DonNicoJs. I'll try dig into the code in order understand the issue. The workaround so far is to compare originalEvent.target and trigger the click method on the proper element, as shown by @disarticulate.

**Comment by disarticulate** [comment]
In other trials of melding Vue with leaflet, particularly with popups, I
would instantiate some dummy element inside a pop-up, then use Vue to
substantiate an instance of a custom component with props and mount that on
the dummy, replacing the dummy element and making the parent an arbitrary
Vue component.  Let me dig up an example at work.

I do agree, it will be difficult to use the Vue templated events directly
inside leaflet.

Each component has a $listeners object, but in OPs example, those docs are
not components, and I could not trace where the click function resides.

**Comment by DonNicoJs** [comment]
@disarticulate @bestmazzo I would be more than happy to provide an out of the box solution if we can find a not so hacky way to deliver it! Let's keep the discussion and possibly examples for @disarticulate Could help. I did some experiment along those lines for marker performances in the past.

Also we need to be wary of the performances too

**Comment by disarticulate** [comment]
Heres how one substantiates a vue component dynamically:
```#vue template
            <v-marker-popup
              v-on:update:attributes="updatePhotoMetadataAttributes"
              ref="popup"
              :options="{
                maxWidth: 'auto',
                className: 'photo-popup'
              }"
              :content="photoPopupContent(photo.fuuid)"
            />
```
```
    photoPopupContent (id) { // static dummy html
      return `<div id="popup-${id}">N/A</div>`
    },
    instantiatePhotoPopup (selector, photo, index) { // pass selector & props
      let ComponentClass = Vue.extend(mapPopup)
      let instance = new ComponentClass({
        propsData: {
          photo,
          index,
          containerId: 'map-area' // let popup know which is the window (must be svg path)
        },
        parent: this.$refs.popup[index]
      })
      instance.$mount(`#${selector}`)
      return instance
    }
```
```#mapPopup component methods of interest:
    closePopup () {
      document.querySelector('.leaflet-popup-close-button').click()
    },
    popupContainer () {
      return this.$parent
    },
    popupObject () {
      return (this.$parent.mapObject)
        ? this.$parent.mapObject
        : null
    },
```

**Comment by disarticulate** [comment]
so this is what leaflet is doing in OP's example (https://jsfiddle.net/nvcqw7d2/2/):
- takes in the html (as html/neutered nodes)
- passed in html element from vue is actually stored as a display:none element

when you do the following in the result thread (console, works in chrome) for jsfiddle:
```
document.querySelectorAll('.myspan')
NodeList(4) [span.myspan, span.myspan, span.myspan, span.myspan]
  0: span.myspan
  1: span.myspan
  2: span.myspan
  3: span.myspan
  length: 4 
  __proto__: NodeList
```
The active vuejs component and binding is still there, and it's replaced by a neutered html element.
```
---neutered
<div style="display: none;"><div><div class="mydiv"><span class="myspan">
              HELLO</span><br> <span class="myspan">
              Goodbye</span></div></div></div>
---live
<div class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" tabindex="0" style="background-position: 0px 0px; margin-left: -6px; margin-top: -6px; width: 12px; height: 12px; transform: translate3d(427px, 237px, 0px); z-index: 237; outline: none;"><div class="mydiv"><span class="myspan">
              HELLO</span><br> <span class="myspan">
              Goodbye</span></div></div>

```

**Comment by disarticulate** [comment]
OK. Here's a minimally working JS Fiddle that demonstrates how one could dynamically instantiate a clickable component inside the l-icon:

https://jsfiddle.net/r6mdgs3w/48/

It's fully transparent for the QBtn component from quasar, in that QBtn has a click function so after completing the instantiation, it'll pass through the click.

There's probably a  clean up problem within Vue if the component is removed by leaflet, but I'd expect it to disappear when the marker is updated.

**Comment by disarticulate** [comment]
fully operational hack, requiring arrive.js: disarticulate/vue-leaflet-icon-wrapper

**Comment by silverbyte** [comment]
as much as I like @disarticulate hack (or solution) to get this working right on the <l-marker @click.native="randFunc()"> makes no sense the event doesn't get triggered when clicking the marker if an icon is assigned on render. Maybe Im missing something but if i CLICK the marker, the function should be called

**Comment by disarticulate** [comment]
The problem appears too be how Leaflet.js treats the HTML it receives. There's two nodes leaflet accounts for:
1. Is a shadow node that holds the element you pass it in the DivIcon class
2. Is a display node that is generated/cloned and not related.

So when you try to @click.native on the visible node, it's not directly connected to what you pass it. Its not  "bug" in the sense that you could, within the framework Vue2-Leaflet is contained, could be fixed, as you'd need to rewire how Leaflet works to clone the underlying DivIcon class.

So my hack is basically using arrive.js to detect when the display node is closed and ready to attach your component directly to it from the shadow node to the element.

If someone _cared_, they'd see if Leaflet.js could be modified to clone the relvent Vue component.

**Comment by Corgis** [comment]
icon  click  it doesn't work
<l-marker :lat-lng="markerLatLng">
    <l-icon
      :icon-anchor="[16, 37]"
      class-name="ui-icon"
      @click="test">
      <img class="ui-img" src="../static/img/H.png" alt="" @click.prevent="test">
    </l-icon>
</l-marker>

**Comment by mathiash98** [comment]
In our scenario we did in fact want buttons to appear after selecting a marker, so we ended up using LPopup instead which does not capture the click event.
