### ISSUE TITLE
@update firing on map load

### ISSUE THREAD

**Issue by chrisgrim** [vue-leaflet/Vue2Leaflet#486]
Hi,
I love this plugin! I have a question about the @update. Right now I am using 
```
@update:bounds="boundsUpdate"
```
This works great except for the fact that it runs when the map first loads. Is there a way to have it only emit a change after the first map load. I tried @change but that didn't work.
Thanks!

**Comment by DonNicoJs** [comment]
@chrisgrim If the event is fired it means that leaflet emitted a `moveend` event, that we subscribe to.
Why is this a problem for your app? Do you think we should not fire the event the 'first time' if so why?

**Comment by chrisgrim** [comment]
Hi @DonNicoJs 
I see. It's good to know how it works behind the scenes. In my app I allow users to search for events using a lat/lng location and elastic search and then return all the events displayed in a list and displayed on the leaflet map.
I don't think it is that big of a deal. I only noticed because I do my first search using elastic search and the 100k radius. Then whenever the user moves the map it does any future elastic searches with the boundary box. So if an event was within the 100k radius, but outside the map border on map load it disappears. 
I was just checking if there was another way to update but the way it works is totally fine for me now.
Thanks for the quick response!!
