### ISSUE TITLE
How to implement noWrap & stop infinite tile loop?

### ISSUE THREAD

**Issue by xlcrr** [vue-leaflet/Vue2Leaflet#494]
Hi,

vue2leaflet tag doesn't exist on stackoverflow apparently and I am just shy of 1,500 points to create the tag so have to post here

How can we stop infinite tile scroll?

I suspect it's something like

```
<l-map :zoom="zoom" :center="center" :noWrap="true" :bounds="maxBounds">
```

```
maxBounds: [[-90, -180],[90, 180]]
```

But this isn't working

**Comment by DonNicoJs** [comment]
@xlcrr what do you mean by infinite tile scroll? like that if you go too much east the map 'turn around'?  you need to enabled: `worldCopyJump` :)

**Comment by xlcrr** [comment]
Hi, thanks for the suggestion. I tried that but no luck

How can I create a tilelayer with just 1 instance of a world map, and not multiple ?

<img width="1792" alt="Screenshot 2019-12-08 at 14 37 00" src="https://user-images.githubusercontent.com/25985241/70391009-344f7e80-19c8-11ea-8582-c8012aa368f5.png">

**Comment by DonNicoJs** [comment]
You need to pass worldCopyJump:true in the options prop :)

**Comment by xlcrr** [comment]
Thanks but it's not working for me 

```
<l-map :zoom="zoom" :center="center" :minZoom="2" :worldCopyJump="true">
```

**Comment by DonNicoJs** [comment]
`<l-map :options="{worldCopyJump:true}" />

**Comment by bdjilka** [comment]
@xlcrr You need to set this attributes not to tag l-map, but to tag l-tile-layer:
`<l-tile-layer:continuousWorld="false" :noWrap="true">`

**Comment by xlcrr** [comment]
Thanks for the tips!

**Comment by chetan-acharya** [comment]
set continuousWorld to false.
https://leafletjs.com/reference-0.7.7.html#tilelayer-continuousworld
