### ISSUE TITLE
Support zoomOffset in GridLayer and descendants

### ISSUE THREAD

**Issue by logi** [vue-leaflet/Vue2Leaflet#495]
This would allow us to use the default 512px tiles generated by MapBox as [described here](https://stackoverflow.com/a/37043490/1228448).

The quick fix is to add `/256/` in the URL and just get the expected smaller but more numerous tiles.

**Comment by DonNicoJs** [comment]
@logi You can already pass it inside the `options` prop! 

`<l-tile-layer :options="{ tileSize: 512 }" .../>`

We then merge that object and feed it to:

` this.mapObject = leaflet.tileLayer(url, options)`

**Comment by logi** [comment]
Ah, TIL.
Thanks.

**Comment by logi** [comment]
Ah, thanks. TIL.
