### ISSUE TITLE
missing markers after update to 2.3.0

### ISSUE THREAD

**Issue by ray007** [vue-leaflet/Vue2Leaflet#497]
#### Description
I've done an `npm update` which installed version `2.3.0` of `vue2-leaflet`.
Since then the markers below the `<l-marker-cluster>` tag do not show up on the map anymore, those directly in the `<l-map>` tag still work.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11 (or v2.6.10)
- Vue2Leaflet: v2.3.0

**Comment by DonNicoJs** [comment]
@ray007 Thanks for the issue, I will check this right now!

**Comment by DonNicoJs** [comment]
@ray007 Are you using `vue2-leaflet-markercluster` from this repo: https://github.com/jperelli/vue2-leaflet-markercluster/blob/master/Vue2LeafletMarkercluster.vue ?

**Comment by DonNicoJs** [comment]
@ray007 I released a patch version that fixes the issue, could you please update the package and let me know?

**Comment by kesm0** [comment]
same issue here ! 
I use jperelli/vue2-leaflet-markercluster: 3.1.0

> @ray007 I released a patch version that fixes the issue, could you please update the package and let me know?
I can't update with 2.3.1, npm install --save vue2-leaflet install 2.3.0 by default

**Comment by DonNicoJs** [comment]
@kesm0 I think there is an issue with npm => `PUT https://registry.npmjs.org/vue2-leaflet - You cannot publish over the previously published versions: 2.3.1.` but 2.3.1 does not appear in the plugin page.

I bumped the version, you can try again to update to 2.3.2

**Comment by kesm0** [comment]
Nice ! @DonNicoJs  Everything is ok for me.
2.3.2 correct the marker cluster problem
Good job !

**Comment by DonNicoJs** [comment]
@kesm0 Thanks for checking right away :) @jperelli I've sent you an invitation to join the organisation if you want to move markercluster plugin!
