### ISSUE TITLE
TypeError thrown due to bad call to propsBinder from LFeatureGroup mounted

### ISSUE THREAD

**Issue by dpr989** [vue-leaflet/Vue2Leaflet#500]
### Description
Hey all! Love Vue2Leaflet and all the work you guys do 13/10! Anyway, I have found what looks like a bug.

There was a change in the way that `propsBinder` method is called in `mounted` of `LFeatureGroup` that seems to pretty clearly breaks all the things.

Commit which introduces the below change
a04c942

```js
// in LFeatureGroup.js

// before commit is applied
propsBinder(this, this.mapObject, this.$options.props);

// after
propsBinder(this, this.mapObject, this);
```

#### Steps to Reproduce
Create LFeatureGroup instance and see error

#### Expected Results
No error to be thrown.

#### Actual Results
TyperError is thrown

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: v2.3.2

**Comment by DonNicoJs** [comment]
@dpr989 I've seen the code comment, investigating this, apologies!

**Comment by DonNicoJs** [comment]
`2.4.2` is out! it should fix this!
