### ISSUE TITLE
Loading Gaode tiles, white lines will appear on the map

### ISSUE THREAD

**Issue by wjzxl** [vue-leaflet/Vue2Leaflet#504]
Loading Gaode tiles, white lines will appear on the map。

safair： iOS13.3

Versions
Leaflet: whatever Vue2Leaflet 1.0.2 uses
Vue: v2.5.16
Vue2Leaflet: v1.0.2

**Comment by DonNicoJs** [comment]
@wjzxl Hi! we need a bit of code, or a bit more to help you

**Comment by wjzxl** [comment]
Thank you for your reply, we have found the reason, it is our own problem, thanks again!
