### ISSUE TITLE
How to use flyTo() function?

### ISSUE THREAD

**Issue by lukas231424** [vue-leaflet/Vue2Leaflet#505]
### Description
I have a nuxt app and I use `nuxt-leaflet`. So I can use `this.$L` as global prototype /instance.
I want to add the flyTo() leaflet animation to my map. If a user clicks on a button, then the my function flying is called.

`flying(pos) {
    this.$L.flyTo([pos.lat, pos.lng], 11);
 },`

#### Expected Results
button  onclick => map view flies to given map point e.g [30.21, 10.32]

#### Actual Results
console gives error: this.$L.flyTo is not a function

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.0
- Vue2Leaflet: v2.4.1

**Comment by DonNicoJs** [comment]
@lukas231424 flyTo is a `map` function, I don't know how nuxt-leaflet handle this but the best way to use it is to add a `@ready` event to `l-map` like so:

`<l-map @ready="handleReady" ... >`

```javascript
handleReady(mapObject) {
mapObject.flyTo(...)
}
```

**Comment by lukas231424** [comment]
thank you dude, it works perfectly
