### ISSUE TITLE
@leafletevent does not work

### ISSUE THREAD

**Issue by alexey2baranov** [vue-leaflet/Vue2Leaflet#507]
### Description
@leafletevent does not emitted anything

#### Live Demo
http://jsfiddle.net/alexey_baranov/vmxhpzLr/

#### Steps to Reproduce
click mouse on map, move map etc..

#### Expected Results
alert(1) in handler should pop up

#### Actual Results
nothing happened

### Browsers Affected
- [ *] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.10
- Vue2Leaflet: v2.2.1

**Comment by DonNicoJs** [comment]
@alexey2baranov well @leafletevent does not exist, the docs mention it as placeholder, you can use any events described in leaflet doc or the ones used in our docs, for example: 

`@ready` or `@locationfound`
