### ISSUE TITLE
this.parentContainer.hideLayer doesn't work

### ISSUE THREAD

**Issue by hoticer** [vue-leaflet/Vue2Leaflet#511]
this.parentContainer.hideLayer doesn't work

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v4.0.5
- Vue2Leaflet: v2.4.1

**Comment by hoticer** [comment]
@DonNicoJs Something is wrong. 
```
<l-map>
  <l-layer-group ref="gridImageLayerGroup" :visible="gridImageLayerGroup.visible">
        <l-layer-group ref="gridImageLayer" :visible="gridImageLayer.visible"/>
        <l-layer-group ref="gridValueLayer" :visible="gridValueLayer.visible"/>
      </l-layer-group>
</l-map>
```
When I set gridImageLayerGroup.visible = false, the gridImageLayer and gridValueLayer are still show. 
I find this reason is that :
in LMap.vue
```
 hideLayer(layer) {
      if (layer.layerType !== undefined) {
        this.mapObject.removeLayer(layer.mapObject);
      }
    },
```
Lmap's  layerType is undefinded. So it doesn't work!

**Comment by JohnnyAW** [comment]
have same issue, my quick fix was to set `layerType` to some value (e.g. "LMarker") on the components

**Comment by DonNicoJs** [comment]
@hoticer  @JohnnyAW I've addressed the issue and publish a new patch version.
I need absolutely to focus on: 
- docs
- ci
- tests

Apologies for the very slow update
