### ISSUE TITLE
Move the zoom-in/zoom-out to another place than upper-left corner

### ISSUE THREAD

**Issue by Mu2tini** [vue-leaflet/Vue2Leaflet#517]
When using Vue2Leaflet and the "l-map" component, is there a way to move the zoom-in/zoom-out buttons to another place than upper-left corner?

https://vue-leaflet.github.io/Vue2Leaflet/#/components/l-map/?id=props

https://i.stack.imgur.com/ITRFr.png

I asked the question on Stackoverflow as well but the tag Vue2Leaflet is not recognized by Stackoverflow not enough mentions.

**Comment by DonNicoJs** [comment]
@Mu2tini you can:
- disable the default zoom controls
- add `l-control-zoom` 
- set `position="topright"` on the `l-control-zoom`

Or which position you prefer :) 

https://vue-leaflet.github.io/Vue2Leaflet/#/components/l-control-zoom/

**Comment by Mu2tini** [comment]
Thank you for the quick answer @DonNicoJs and a great component!

**Comment by mashirozx** [comment]
but how to disable the default zoom controls? LAL

**Comment by mashirozx** [comment]
> > but how to disable the default zoom controls? LAL
> 
> By setting the [`zoomControl` option](https://leafletjs.com/reference-1.7.1.html#map-zoomcontrol) to `false` on the map, e.g. `<l-map :options="{ zoomControl: false }" ...>`

thanks a lot
