### ISSUE TITLE
Weird render on own sliding panel

### ISSUE THREAD

**Issue by sztomczyk** [vue-leaflet/Vue2Leaflet#519]
Hi, I wanna put map on sliding panel. Everything is ok when map renders instantly after page loads. Problems come when I put map inside togglable div.

I import CSS correctly:
```js
// Leaflet
import { Icon } from "leaflet"
import "leaflet/dist/leaflet.css"
```

![image](https://user-images.githubusercontent.com/28072430/73864181-7cace080-4841-11ea-9d31-b4f0bbab603b.png)

**Comment by DonNicoJs** [comment]
@sztomczyk you need to manually trigger a re-render of the map, put a ref on `l-map` component and call https://leafletjs.com/reference-1.6.0.html#map-invalidatesize
