### ISSUE TITLE
ERR_NAME_RESOLUTION_FAILED

### ISSUE THREAD

**Issue by Meti27** [vue-leaflet/Vue2Leaflet#520]
thank for awesome package.
i implement it some days ago and it was perfect , but now its say `ERR_NAME_RESOLUTION_FAILED`.

![image](https://user-images.githubusercontent.com/11253027/74086432-fccc8380-4a97-11ea-9d69-664ab97caaa7.png)

```js
    data: {
        zoom: 10,
        center: [35.71634907, 51.39087920],
        markerLatLng: [35.71634907, 51.39087920],
        url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
    },
```
and html : 
```js 
<l-map ref="myLocation" :zoom="zoom" :center="center" style="height: 100% !important; width: 100%">
    <l-tile-layer :url="url"></l-tile-layer>
    <l-marker :lat-lng="center" :draggable="false">
    </l-marker>
</l-map>
```

**Comment by Meti27** [comment]
got it .
base on [switch2osm](https://switch2osm.org/using-tiles/getting-started-with-leaflet/) i change the `url` to: 

```js
url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
```
and its working perfect again.

**Comment by DonNicoJs** [comment]
@Meti27 Thanks for opening this issue! I actually have to update all the examples as well :)
