### ISSUE TITLE
OpenStreetMap URL incorrect in examples

### ISSUE THREAD

**Issue by ajmas** [vue-leaflet/Vue2Leaflet#521]
### Description

From what I can see the correct URL for OpenStreepMap tiles should be:

https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

based on https://leafletjs.com/

Current examples reference http://{s}.tile.osm.org/{z}/{x}/{y}.png, which cause errors.

#### Live Demo

Breaking example:

http://jsfiddle.net/Boumi/k04zpLx9/

JSFiddle isn't working properly for saving at the moment, but the modified JS:

```
var { LMap, LTileLayer, LMarker } = Vue2Leaflet;

new Vue({
  el: '#app',
  components: { LMap, LTileLayer, LMarker },
  data() {
    return {
      zoom:13,
      center: L.latLng(47.413220, -1.219482),
      url:'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      attribution:'&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      marker: L.latLng(47.413220, -1.219482),
    }
  }
});
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: 1.6.0
- Vue: 2.6.11
- Vue2Leaflet: v2.4.3

**Comment by MaurizioRicci** [comment]
I confirm the strange problem; As the docs says there should be no difference beetween the two form of urls.

> When we type in the web browser the short address of the OpenStreetMap, http://OSM.ORG, the browser quickly transforms the URL in a new one, https://www.openstreetmap.org. This transformation, named "URL forwarding" or URL redirection, is a fundamental Web mechanism, technically knowed also as HTTP status 301. The URL that was quickly transformed into the final one, is said "an alias" of the final one.
Taken by: https://wiki.openstreetmap.org/wiki/Short_URL

**Comment by DonNicoJs** [comment]
@ajmas thanks for the issue! I am about to release the new docs  and examples where I fixed the issue!

**Comment by DonNicoJs** [comment]
@ajmas @MaurizioRicci  I've just deployed the new docs: https://vue2-leaflet.netlify.com/ enjoy!
