### ISSUE TITLE
Docs not accessable

### ISSUE THREAD

**Issue by maratumba** [vue-leaflet/Vue2Leaflet#523]
### Description

The docs page has dissappeared: https://vue-leaflet.github.io/Vue2Leaflet/

#### Live Demo

https://vue-leaflet.github.io/Vue2Leaflet/

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x]  Safari 9
- [x] Safari 8
- [x] IE 11

**Comment by DonNicoJs** [comment]
@maratumba You caught me mid update :)  The docs are available again, new url: https://vue2-leaflet.netlify.com/

Old url setup as a redirect

**Comment by maratumba** [comment]
I'm lucky like that. Thanks for all the great work!

**Comment by maratumba** [comment]
Umm, the links at components page not working, it this also because of the update?

https://vue2-leaflet.netlify.com/components/

**Comment by DonNicoJs** [comment]
@maratumba Direct links do not work at the moment due to a bug :( Sorry it was not present in dev mode. I will fix it soon, in the meatime you can access the components by going to the root of the docs and then navigating to them!
