### ISSUE TITLE
Docs: Components page links are broken

### ISSUE THREAD

**Issue by maratumba** [vue-leaflet/Vue2Leaflet#524]
### Description

E.g. `l-circle` link url in components page is https://vue2-leaflet.netlify.com/components/LCircle and is broken, whereas on the sidebar, the url is https://vue2-leaflet.netlify.com/components/LCircle.html

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

**Comment by DonNicoJs** [comment]
@maratumba Fixed! Thanks :)
