### ISSUE TITLE
new docs: links and codesandbox examples

### ISSUE THREAD

**Issue by udos** [vue-leaflet/Vue2Leaflet#525]
well done @DonNicoJs! nice!

I noticed the following. while navigating to

- https://vue2-leaflet.netlify.com

works perfectly, navigating to a path (by clicking the link or pasting it in the browser) e.g.

- https://vue2-leaflet.netlify.com/quickstart/

ends with:
![image](https://user-images.githubusercontent.com/141107/74140422-54343600-4bf5-11ea-94f6-361787d870ee.png)

codesandbox examples are broken. e.g. when clicking in

- https://vue2-leaflet.netlify.com/components/LMap.html#demo

the codesandbox icon
![image](https://user-images.githubusercontent.com/141107/74140677-d45a9b80-4bf5-11ea-80dd-1af35020ec0a.png)

the sandbox

- https://codesandbox.io/s/vo41q

opens, displaying the following:
![image](https://user-images.githubusercontent.com/141107/74140845-28fe1680-4bf6-11ea-9387-55cadc94a5fa.png)

**Comment by DonNicoJs** [comment]
@udos Thanks for the report! Yes I am aware of the issue which sadly was not displaying in the dev mode :( 

The issue is that is difficult to have vue-press compile properly while having as clean as possible examples ( do to leaflet iteslf not being compatible with server side rendering )

I am working on it :)

**Comment by DonNicoJs** [comment]
@udos The docs links are all fully functional, regarding the codesandbox issue I am afraid there is a problem with the code itself, I did not do many changes but I added a utility function. I will investigate this issue soon!

If anyone has more material / info like:

2.5.1 works locally on vue-cli
2.5.1. do not work locally on nuxt

that would be awesome 😄

**Comment by DonNicoJs** [comment]
@udos I ended up reverting some of the changes.. 2.5.2 should be good to go.
I noticed that code sandbox still fails, but clicking on the `refresh` button in the dependency list fixes the issue so I guess is some caching on their end! Please let me know if this reliably solve the issue

**Comment by udos** [comment]
well done! probably tricky to figure it out:
![image](https://user-images.githubusercontent.com/141107/74170263-ef94cd80-4c2c-11ea-9efc-df17c6f154de.png)
