### ISSUE TITLE
'L' is not defined, unless leaflet is explicitly imported

### ISSUE THREAD

**Issue by ajmas** [vue-leaflet/Vue2Leaflet#526]
### Description

When following the examples, such as with:

https://vue2-leaflet.netlify.com/components/LIcon.html#demo

we see references to 'L', such as in:

```
      icon: L.icon({
        iconUrl: '/images/baseball-marker.png',
        iconSize: [32, 37],
        iconAnchor: [16, 37]
      }),
```

Looking at the documentation it is not clear how to a new user how to address this.

My solution was simply to add the following line:

```
import L from 'leaflet'.
```

In my particular case I am using Vue by means of Quasar, but even with plain Vue, where were are using vue-cli to create the project this is likely to be an issue.

I tested in Chrome, but this will likely impact all environments.

#### Live Demo

n/a

#### Expected Results

Should probably update the documentation to indicate import of 'leaflet', rather than simply including in the package.json

#### Actual Results

Since `L` is not imported from anywhere when using a packaged Vue project, as opposed to once where it is imported, along with leaflet, from a CDN:

```
'L' is not defined
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: 1.6.0
- Vue: 2.6.11
- Vue2Leaflet: 2.5.1

**Comment by DonNicoJs** [comment]
@ajmas Thanks for the detailed post! As it is with the new docs I simply imported all the old examples, and just fixed what it needed to be  fixed, I guess there is much work still to refine then! I am going to mark this issue as `help wanted`
