### ISSUE TITLE
Apply LMarker on Geojson

### ISSUE THREAD

**Issue by HamHamFonFon** [vue-leaflet/Vue2Leaflet#542]
Hi,
I'm building a map with two geojson (loaded by axios) and i would like to apply differents markers for each geojson but i don't find how to merge `l-geo-json` , `l-marker` and `l-icon`

Here's my code example : 
https://jsfiddle.net/HamHamFonFon/p3Lsf6d1/9/

Default icon style is still applying and i don't know how to fix it.
Thanks for help :).

### Versions
- Leaflet: v1.5.8 (not sure)
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by HamHamFonFon** [comment]
Resolved with pointToLayer function

**Comment by 0wenwu** [comment]
> 
> 
> Resolved with pointToLayer function

how to use this function?

**Comment by HamHamFonFon** [comment]
https://github.com/HamHamFonFon/deep-space-objects/blob/master/assets/js/Widgets/Observation/List.vue#L65 
`
<l-geo-json v-if="(itemselect === 'event') || (itemselect === 'all')"
              :geojson="geojsonEvents"
              :options="optionsEvents"
              name="l_events"
            >
`

Then : https://github.com/HamHamFonFon/deep-space-objects/blob/master/assets/js/Widgets/Observation/List.vue#L181

**Comment by 0wenwu** [comment]
> https://github.com/HamHamFonFon/deep-space-objects/blob/master/assets/js/Widgets/Observation/List.vue#L65 
> 
> `
> 
> <l-geo-json v-if="(itemselect === 'event') || (itemselect === 'all')"
> 
>               :geojson="geojsonEvents"
> 
>               :options="optionsEvents"
> 
>               name="l_events"
> 
>             >
> 
> `
> 
> 
> 
> Then : https://github.com/HamHamFonFon/deep-space-objects/blob/master/assets/js/Widgets/Observation/List.vue#L181
> 
> 

Thx, it really works for me

**Comment by HamHamFonFon** [comment]
> Thx, it really works for me
You're welcome :)
