### ISSUE TITLE
'Marker icons are missing' section in docs needs a note for TypeScript developers

### ISSUE THREAD

**Issue by geopic** [vue-leaflet/Vue2Leaflet#543]
### Description

The fix for missing marker icons in the docs is awkward for TypeScript developers as it provokes a TS2339 error (`_getIconUrl` is not accessible on `Icon.Default`). Novice TypeScript users may not know how to rectify this. I propose an addition to the code sample so it is made clear what to do in solving the error:

```ts
type D = Icon.Default & {
  _getIconUrl: string;
};

delete (Icon.Default.prototype as D)._getIconUrl;
```

#### Live Demo

N/A

#### Steps to Reproduce

Start a Vue project which includes TypeScript and attempt to run `npm run serve` command or use an IDE with a TypeScript extension. You will get a TS2339 error in `main.ts`.

#### Expected Results

N/A

#### Actual Results

N/A

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by DonNicoJs** [comment]
@geopic Thanks for the issue! Will you be able to submit a PR about it? It would be really appreciated!

**Comment by geopic** [comment]
Sure @DonNicoJs, I'll get on it now.
