### ISSUE TITLE
Can't figure how to add tooltip on Polygon

### ISSUE THREAD

**Issue by fbmfbm** [vue-leaflet/Vue2Leaflet#546]
Hi all,

I can't figure how to use tooltip with polygone...
It's working well on marker but can't add it to polygon or feature_group with polygon without marker.
Any one can point me to some exemple ?
Thank's a lot.

fbm

**Comment by DonNicoJs** [comment]
@fbmfbm Hey! you can add a tooltip or a popup by altering a bit this example: 

https://vue2-leaflet.netlify.com/examples/popup-on-geometry.html

**Comment by fbmfbm** [comment]
Hello DonNicoJs ! thank's for your answer.
Ok. I have read this exemple before,  but as i can add popup to polygon, tooltip is not working.
I'll try one more time.

**Comment by fbmfbm** [comment]
My apologies !! 
it's working.
i can add the sticky options to.
Thank's
