### ISSUE TITLE
Support click on map to get GetFeatureInfo

### ISSUE THREAD

**Issue by starofsky** [vue-leaflet/Vue2Leaflet#547]
Hi,
Can you support function get GetFeatureInfo when click on layerWMS like below link?

https://gist.github.com/rclark/6908938#file-l-tilelayer-betterwms-js

Thank you so much.

**Comment by DonNicoJs** [comment]
@starofsky I am not sure what is your request exactly, could you explain a bit more?

**Comment by starofsky** [comment]
> 
> 
> @starofsky I am not sure what is your request exactly, could you explain a bit more?

Hi @DonNicoJs ,
I mean, can we GetFeatureInfo request in WMS when we click on map?
When we click on map, we will get coordinate and build URL to request GetFeatureInfo service.
Ex:

`function (latlng) {
    // Construct a GetFeatureInfo request URL given a point
    var point = this._map.latLngToContainerPoint(latlng, this._map.getZoom()),
        size = this._map.getSize(),
        
        params = {
          request: 'GetFeatureInfo',
          service: 'WMS',
          srs: 'EPSG:4326',
          styles: this.wmsParams.styles,
          transparent: this.wmsParams.transparent,
          version: this.wmsParams.version,      
          format: this.wmsParams.format,
          bbox: this._map.getBounds().toBBoxString(),
          height: size.y,
          width: size.x,
          layers: this.wmsParams.layers,
          query_layers: this.wmsParams.layers,
          info_format: 'text/html'
        };
    
    params[params.version === '1.3.0' ? 'i' : 'x'] = point.x;
    params[params.version === '1.3.0' ? 'j' : 'y'] = point.y;
    
    return this._url + L.Util.getParamString(params, this._url, true);
  }`

**Comment by DonNicoJs** [comment]
This sounds like a request for a new plugin :) please feel free to create one!

**Comment by mgrobito** [comment]
Hello @DonNicoJs sir,
Any update about this GetFeatureInfo . If there is plugin exist where can i find it?
