### ISSUE TITLE
#35

### ISSUE THREAD

**Issue by andrewGIS** [vue-leaflet/Vue2Leaflet#549]
Hi, all. 
Is it possible to call native method of Lefalet WMS Tile Layer ? Layer does not update when CQL_FILTER is changed ? May be any other way to refresf a WMS Layer ?

**Comment by DonNicoJs** [comment]
Hi let me know if this solve your issue: 
https://vue2-leaflet.netlify.com/faq/#how-can-i-access-the-leaflet-map-object

**Comment by andrewGIS** [comment]
> Hi let me know if this solve your issue:
> https://vue2-leaflet.netlify.com/faq/#how-can-i-access-the-leaflet-map-object
Thanks, for mapObject name mapObject. What is the name of other components? In my case WMS Layer ? WMSObject?

**Comment by DonNicoJs** [comment]
@andrewGIS It's always mapObject indipendently from the component! if in the future you have more questions please join us on discord: https://discord.gg/uVZAfUf

**Comment by andrewGIS** [comment]
> @DonNicoJs. Thanks, but in console I didn't find method called **redraw**.

**Comment by andrewGIS** [comment]
Here is my code . This layer is inside l-map tag. As you see :options bind with computer property.
`<l-wms-tile-layer ref="wms1"
              :base-url="baseUrl"
              :visible="true"
              format="image/png"
              layers="ucc:dev_mosaic"
              :transparent="true"
              :opacity=0.5
              :options="WMSOptionsMap1"/>`
Computed property below. It just returns expression from Vuex. Condition is correct, when set it manually from VueDevtools.It is correct, but not "reactive". It doesn't change when condition update. In mapObject instance of wmsLayer there is not aviable method redraw as in native leaflet library. 
 `WMSOptionsMap1 () {
      return {
        CQL_Filter: this.$store.getters.GET_MAP_FILTER(1)`

**Comment by andrewGIS** [comment]
Solve it by add method redraw in LWMSTileLayer.js  
`    updateVisibleProp: function updateVisibleProp(value) {
      this.$emit('update:visible', value);
    }
    ,
    redraw: function redraw(){
      this.redraw()
    }`
Then after get it as refs in data refresh 
`this.wms1.wmsParams.CQL_FILTER = `${this.$store.getters.GET_MAP_FILTER(1)}`
 this.wms1.redraw()`
