### ISSUE TITLE
how do i calculate zoom lvl dynamically in order to contain multiple places?

### ISSUE THREAD

**Issue by mtalhabalci** [vue-leaflet/Vue2Leaflet#550]
I'm working with vue2leaflet and in my story there can be one or more objects signed on the map.
For example one polygon can be in one place of the world and the other one in another place. here there are two polygons and my zoom level has to be dynamic so that both points will be visible. also the points can be so close to each other and can show a very small polygon. here zoom level has to increase. as i see your documentation, you've always given the zoom statically. 

i'll also try to explain my issue with images.
![leafletIssue](https://user-images.githubusercontent.com/47703652/75518460-fcc60080-5a11-11ea-9d5a-0fc1e0d5747b.PNG)

here there are two big polygons and they are far from each other.

while;

![leafletIssue2](https://user-images.githubusercontent.com/47703652/75518771-bd4be400-5a12-11ea-8ae5-9f97805e03ae.PNG)
in this image the polygons are close to each other and they show very small pieces.

I need to calculate zoom level in accordance with my polygons.
Thanks.

**Comment by DonNicoJs** [comment]
@mtalhabalci You should nest your polygons inside a `l-feature-group` and then you can use the bounds of it to calculate the center and zoom of the map: https://leafletjs.com/reference-1.6.0.html#featuregroup

**Comment by DonNicoJs** [comment]
If this works for you could you please consider adding a new section to our docs? :)

**Comment by bradley-varol** [comment]
How do i use `getBounds()`? `this.$refs.featureGroup.getBounds()` is undefined.

**Comment by sowinski** [comment]
Same problem here.

**Comment by DJLawton** [comment]
@bradley-varol Try `this.$refs.featureGroup.mapObject.getBounds()` instead.
[https://vue2-leaflet.netlify.app/components/LFeatureGroup.html](url)
