### ISSUE TITLE
Same coordinates different places

### ISSUE THREAD

**Issue by mtalhabalci** [vue-leaflet/Vue2Leaflet#551]
Hello people
I'm using vue2leaflet. I have a simple but important issue.
I get coordinates from http://geojson.io/ and virtuliaze it in vue2leaflet.
The places are different.

![vue2leafletDifferentPlace](https://user-images.githubusercontent.com/47703652/75521142-2124db80-5a18-11ea-86ef-844cbac8c9fd.PNG)

this is the polygon i get from http://geojson.io

unfortunately the vue2leaflet output is like this;

![vue2leafletDifferentPlace2](https://user-images.githubusercontent.com/47703652/75521237-5b8e7880-5a18-11ea-9e89-7c625924bb8e.PNG)

i also tried this with another websites that virtualizes polygons on map.
leaflet's output was different.
i would be thankful if someone could help me.

**Comment by DonNicoJs** [comment]
@mtalhabalci It looks like a CRS issue I guess! this is probably a leaflet issue and not a vue2-leaflet issue. Please reach out to the leaflet repo.

If you need more assistance join us on Discord, you can find the invite in the main readme
