### ISSUE TITLE
Cannot use flyTo method, it's marked as "... is not a function"

### ISSUE THREAD

**Issue by mStolvrczyk** [vue-leaflet/Vue2Leaflet#552]
Hello everyone, I'm creating simple app for monitoring air pollution in my country. I've got map with pins for every station. When I click on every pin center changes it's coordinates to coordinates of a given station - it works correct, but i want the effect of map position change to become smooth. I've read that I can achieve that with flyTo function, but when I'm trying to use it, it gives me "TypeError: this.$refs.map.panTo is not a function". What am I doing wrong? Refference to map object is correct, because other functions like setZoom are working well. My version of leaflet is 1.5.1, vue2-leaflet is 2.2.1. 
My map component looks like this:

![ss1](https://user-images.githubusercontent.com/44430195/75613622-2f661b00-5b30-11ea-848a-efdc952a9f3b.png)

and the method:

![ss2](https://user-images.githubusercontent.com/44430195/75613601-cbdbed80-5b2f-11ea-945b-080dcd843178.png)

I will be grateful for your help!

**Comment by DonNicoJs** [comment]
@mStolvrczyk  you need to change the method to:

`this.$refs.map.mapObject.flyTo(...)`

If you still have trouble join us on discord :) the link is in the main readme

**Comment by jonmes** [comment]
It is renamed to leafletObject in vue 3
`map.value.leafletObject.flyTo([randomLat, randomLong], 12)`
