### ISSUE TITLE
async keyword throwing an error after Vue2Leaflet's installation (async created hook)

### ISSUE THREAD

**Issue by stephan-wdd** [vue-leaflet/Vue2Leaflet#554]
#### Sample code
```
<template>
  <l-map style="height: 350px" :zoom="zoom" :center="center">
    <l-tile-layer :url="url"></l-tile-layer>
    <l-geo-json :geojson="geojson"></l-geo-json>
  </l-map>
</template>

<script>
import {LMap, LTileLayer, LGeoJson} from 'vue2-leaflet';
export default {
  components: {
    LMap,
    LTileLayer,
    LGeoJson
  },
  data () {
    return {
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      zoom: 8,
      center: [47.313220, -1.319482],
      geojson: null
    };
  },
  async created () {
    const response = await fetch('https://rawgit.com/gregoiredavid/france-geojson/master/regions/pays-de-la-loire/communes-pays-de-la-loire.geojson');
    this.geojson = await response.json();
  }
}
</script>

```

#### Expected Results
To run normally.

#### Actual Results
C:\HOME\leaflet\mapexample>npm run serve

> mapexample@0.1.0 serve C:\HOME\leaflet\mapexample
> vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin
 ERROR  Failed to compile with 3 errors                                 18:35:04

These dependencies were not found:
* core-js/modules/es.object.to-string in ./node_modules/@babel/runtime/helpers/e
sm/asyncToGenerator.js, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./nod
e_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./n
ode_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?v
ue&type=script&lang=js&
* core-js/modules/es.promise in ./node_modules/@babel/runtime/helpers/esm/asyncT
oGenerator.js

To install them, you can run: npm install --save core-js/modules/es.object.to-st
ring core-js/modules/es.promise

### Versions
  "dependencies": {
    "core-js": "^3.6.4",
    "leaflet": "^1.6.0",
    "vue": "^2.6.11",
    "vue2-leaflet": "^2.5.2"

I am getting this error related to the use of generator/async keyword in the created lifecycle hook. Please note that **async created hook worked fine before installing vue2-leaflet** so this scenario has been tested.
I have only tested an example that can be found in the vue2-leaflet directory. It works fine as soon as I remove the async keyword. 

I am on Windows 7 64bit home edition.

**Comment by DonNicoJs** [comment]
@stephan-wdd This is very weird, and I guess somehow your `node_modules` got messed up, to be able to help you here I would need a reproduction repo in the meantime you can try to:

- wipe `node_modules` and re-install
- remove core-js from the dependencies
