### ISSUE TITLE
`ready` event not firing

### ISSUE THREAD

**Issue by maratumba** [vue-leaflet/Vue2Leaflet#555]
### Description

Ready event not fired from `l-map` component.

#### Live Demo

https://jsfiddle.net/gulyamani/omvygLqp/6/

#### Steps to Reproduce
Open console, refresh the page

#### Expected Results

Seeing `ready` in console output

#### Actual Results

Not seeing `ready` in console output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.0.3
- Vue: v2.5.16
- Vue2Leaflet: v1.0.1

**Comment by DonNicoJs** [comment]
@maratumba The fiddle do not run for me for some reason :( could you try to start with the codesanbox generated by the docs? 
Thanks and sorry for the late reply!

**Comment by maratumba** [comment]
I used the code as template in the issue template:
```
#### Live Demo
<!-- Fork this JSFiddler, or provide your own URL -->
http://jsfiddle.net/Boumi/k04zpLx9/

#### Steps to Reproduce
```

I'm afraid I don't know where the codesandbox link is.

**Comment by DonNicoJs** [comment]
@maratumba I need to fix the issue template as well 😄 here is a codesandbox: https://codesandbox.io/s/4hp6t

In the docs, each component has a demo code and a button to open codesanbox: https://vue2-leaflet.netlify.com/components/LMap.html#demo

**Comment by maratumba** [comment]
Seems to be working in [codesandbox ](https://codesandbox.io/s/jolly-haibt-x40qd) but it is not working for me locally.
