### ISSUE TITLE
How to accessing leaflet api ?

### ISSUE THREAD

**Issue by b31zakx96** [vue-leaflet/Vue2Leaflet#556]
Hello everyone,

i'm using vue2leaflet and when i'm trying to use any leaflet function or a plugin i just can't do it ,note that i was read this code in the documentation `this.$nextTick(() => {
        this.$refs.myMap.mapObject.ANY_LEAFLET_MAP_METHOD();
      });` by adding the ref to my map. but still cant handle it. 
the think that i can't see if i want to run this for exemple : `L.marker([lat, lat]).addTo(map)` so it should ` this.$refs.myMap.mapObject.L.marker([lat, lat]);` but what makes up for this `addTo(map)` in order to appear in the map.

like i want just a simple example how to use it with mapObject and i can understand how its work and do the same. 

thanks.

**Comment by DonNicoJs** [comment]
@b31zakx96 this is a very weird code :) if you want to create a marker why not use `LMarker` directly? If you need more assistance please join us on discord ( the link is in the README )

**Comment by b31zakx96** [comment]
@DonNicoJs because i'm new with vue & leaflet that why, but it's just an exemple because i already used `<l-marker>` tag directly. i'm looking to use leaflet sidebar v2 plugin `var sidebar = L.control.sidebar('sidebar').addTo(map);` that why i need to accessing leaflet api.
Anyway thanks for the comment and i will definitely join the discord
