### ISSUE TITLE
Issue with marker Icon not appearing on server

### ISSUE THREAD

**Issue by chrisgrim** [vue-leaflet/Vue2Leaflet#557]
The marker Icons appear on my local server but disappear as soon as I run my project on digital ocean. I did research and found the code below but still I am getting the missing files error.
```
// this part resolve an issue where the markers would not appear
delete Icon.Default.prototype._getIconUrl;
Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});
```
The url that it is looking for the files is /images/vendor/leaflet/dist/marker-icon-2x.png?401d815dc206b8dc1b17cd0e37695975.

**Comment by DonNicoJs** [comment]
@chrisgrim Where did you add the above code? We need a bit more code to help, also please join us on discord if you want to talk this more ( the link is in the README )
