### ISSUE TITLE
Ability to show only one country only

### ISSUE THREAD

**Issue by Abel-Moremi** [vue-leaflet/Vue2Leaflet#561]
A feature that allows taking in a GeoJSON and only loading contents within the Polygon in the most efficient way possible. Similar to what this [repo here](https://github.com/aparshin/leaflet-boundary-canvas) does for Leaflet.

**Comment by DonNicoJs** [comment]
@Abel-Moremi you can already achieve it with the `@ready` event on `l-geo-json` and then use `fitToBounds` ( or similarly named function )

**Comment by Abel-Moremi** [comment]
@DonNicoJs  oh cool will look into that... my bad
