### ISSUE TITLE
LRectangle's bounds require Array

### ISSUE THREAD

**Issue by iBobik** [vue-leaflet/Vue2Leaflet#564]
### Description

Bounds prop of rectangle does not accept latLngBounds object from Leaflet even if Leaflet's [Rectangle supports](https://leafletjs.com/reference-1.6.0.html#rectangle-l-rectangle) it.

#### Steps to Reproduce
```
  computed: {
    bounds () {
      return new LatLngBounds(this.poiPages.map(page => page.content.gps));
    }
  },
```
```
<l-rectangle :bounds="bounds" />
```

#### Expected Results

Will accept also Leaflet's bounds object.

#### Actual Results

[Vue warn]: Invalid prop: type check failed for prop "bounds". Expected Array, got Object 

### Browsers Affected

all

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

### Workaround
Convert object to array:
```
  computed: {
    bounds () {
      return Object.values(new LatLngBounds(this.poiPages.map(page => page.content.gps)));
    }
  },
```

**Comment by DonNicoJs** [comment]
@iBobik Thank you for the issue! will fix
