### ISSUE TITLE
After update to 2.5.x - Module parse failed: Unexpected character '#' 

### ISSUE THREAD

**Issue by alicja-m** [vue-leaflet/Vue2Leaflet#566]
### Description
Error on `npm run serve` after updating vue2leaflet to 2.5.x version:
```
Module parse failed: Unexpected character '#' (86:0)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|
> ## Demo
| ::: demo
| <template>

 @ ./node_modules/vue2-leaflet/src/components/LGeoJson.vue?vue&type=custom&index=0&blockType=docs 

```

#### Expected Results
The module should be properly parsed.

#### Actual Results
Error is thrown.

### Versions
- Leaflet: 1.6.0
- Vue:  2.6.11
- Vue2Leaflet: > 2.5.0 (for 2.4.x everything is ok)

**Comment by DonNicoJs** [comment]
@alicja-m How are you imporing `vue2-leaflet` it seems that you are trying to consume the raw `sfc` files, sorry for the slow answer!
