### ISSUE TITLE
Trying to adapt Leaflet.migration plugin but failing

### ISSUE THREAD

**Issue by h4gen** [vue-leaflet/Vue2Leaflet#573]
### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2
- Leaflet.Migration: v2.0.5

Hello,

I am pretty new to frontend stuff, vue and JS. Nevertheless I tried to adapt the [Leaflet.Migration Plugin](https://github.com/lin-123/leaflet.migration) into an Vue2Leaflet Plugin.

I followed the example of other plugins which were adapted to Vue2Leaflet, namely:

- [Hotline](https://github.com/ikmolbo/vue2-leaflet-hotline)
- [Choropleth](https://github.com/voluntadpear/vue-choropleth)
- [Rotated Marker](https://github.com/mudin/vue2-leaflet-rotatedmarker)

I think I did pretty good so far but sadly the effect won't show up on the map. I would be really grateful for every hint! 

This is the .vue Component that I wrote:

```vue
<template>
  <div style="display: none;">
    <slot v-if="ready"></slot>
  </div>
</template>

<script>
import 'leaflet.migration'

import { DomEvent } from 'leaflet'
const { findRealParent, propsBinder } = require('vue2-leaflet')

const props = {
  visible: {
    type: Boolean,
    custom: true,
    default: true
  },
  labels: {
    type: Array,
    custom: true,
    default: () => ['A', 'B'] // Defaults to exclude possibility of wrongly plugged setting 
  },
  from: {
    type: Array,
    custom: true,
    default: () => [20, 20]
  },
  to: {
    type: Array,
    custom: true,
    default: () => [50, 50]
  },
  color: {
    type: String,
    custom: true,
    default: "AFAFAF"
  },
  value: {
    type: Number,
    custom: true,
    default: 3
  },
  pulseRadius: {
      type: Number,
      custom: true,
      default: 10
  },
  arcWidth: {
      type: Number,
      custom: true,
      default: 1
  },
  label: {
      type: Boolean,
      custom: true,
      default: true
  },
}

export default {
  name: 'LMigrationLayer',
  props: props,
  data () {
    return {
      ready: false
    }
  },
  mounted () {

    const options = {};
    const data = {}

    if (this.pulseRadius) {
      options.pulseRadius = this.pulseRadius;
    }
    if (this.arcWidth) {
      options.arcWidth = this.arcWidth;
    }
    if (this.label) {
      options.label = this.label;
    }

    if (this.labels) {
      data.labels = this.labels;
    }
    if (this.from) {
      data.from = this.from;
    }
    if (this.to) {
      data.to = this.to;
    }
    if (this.color) {
      data.color = this.color;
    }
    if (this.value) {
      data.value = this.value;
    }

    this.mapObject = window.L.migrationLayer(data, options)

    DomEvent.on(this.mapObject, this.$listeners);
    propsBinder(this, this.mapObject, props);
    this.ready = true;
    this.parentContainer = findRealParent(this.$parent);
    this.parentContainer.addLayer(this, !this.visible);
  },
  beforeDestroy () {
    this.parentContainer.removeLayer(this);
  },
  methods: {

    setData (newVal) {
      this.mapObject.setData(newVal)
    },
    setStyle (newVal) {
      this.mapObject.setStyle(newVal)
    },
    setVisible (newVal, oldVal) {
      if (newVal === oldVal) return
      if (this.mapObject) {
        if (newVal) {
          this.parentContainer.addLayer(this);
        }
        else {
          this.parentContainer.removeLayer(this.mapObject)
        }
      }
    }
  }
}
</script>

```
The component seems to be correctly recognized by Vue:
![image](https://user-images.githubusercontent.com/12556763/80319583-66476d00-8811-11ea-9c4a-076b81ec7963.png)

All the properties of the component seem to be set correctly and ready is set to `true`:
![image](https://user-images.githubusercontent.com/12556763/80319601-9131c100-8811-11ea-9047-a55448069bdb.png)

Also the adapter to the JS object seems to be fine as all attributes are set correctly:
![image](https://user-images.githubusercontent.com/12556763/80319689-11f0bd00-8812-11ea-9b24-9faba9273267.png)

And the object seems to be correctly added to the parent Map object:
![image](https://user-images.githubusercontent.com/12556763/80319738-4c5a5a00-8812-11ea-8c54-c7357c4980e1.png)

The only odd thing is that the div from my component is not correctly recognized or evaluated:
![image](https://user-images.githubusercontent.com/12556763/80319793-be32a380-8812-11ea-868d-9edc1edd74ff.png)

The console has **no** errors.

I think that something goes wrong with the following part
```vue
  <div style="display: none;">
    <slot v-if="ready"></slot>
  </div>
```
as the div does not seem to be evaluated correctly. I don't understand why as the value of `ready` seems to be changed correctly after mounting.

Thanks for any hint!

**Comment by h4gen** [comment]
Okay I found the solution and the problem sat in front of the computer. The plugin needs the data as a list. `this.mapObject = window.L.migrationLayer([data], options)` solved the problem. So adaptation is working fine now. Thanks!

**Comment by empereira** [comment]
hey @h4gen ,

Were you able to use the vue-choropleth along with the vue-leaflet? Could you show an example?
