### ISSUE TITLE
Tiles misplaced

### ISSUE THREAD

**Issue by mnboos** [vue-leaflet/Vue2Leaflet#577]
### Description
The tiles are misplaced (according to the screenshot)

![image](https://user-images.githubusercontent.com/22575883/80785912-3df99e80-8b82-11ea-8fcc-e163396bd96c.png)

I used exactly this code: https://vue2-leaflet.netlify.app/components/LTileLayer.html#demo

#### Live Demo
None

#### Steps to Reproduce
Copy the past from the guide.

#### Expected Results
Correctly placed tiles

#### Actual Results
Incorrectly placed tiles

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by pr0ph0z** [comment]
Have you imported the CSS files?

**Comment by fc7** [comment]
I had the same issue, the problem was that I was trying to import the leaflet.css in my public/index.html using the tilde prefix (referring to the NPM package)
```html
<link rel="stylesheet" href="~leaflet/dist/leaflet.css">
```
but this convention only works from inside a Vue component. Moving it to the <style> section of App.vue solved it:
```css
@import url("~leaflet/dist/leaflet.css");
```

**Comment by michealjroberts** [comment]
For me, I stupidly forgot I was purging css in production, so I needed to add a few whitelists to the `whitelistPatterns` attribute:

```
const postcssPurgecss = require(`@fullhuman/postcss-purgecss`);

const purgecss = postcssPurgecss({
	// Specify the paths to all of the template files in your project.
	content: [
	  './public/**/*.html',
	  './src/**/*.vue',
		'./src/**/*.js',
		'./src/**/*.svg',
	],
	// Include any special characters you're using in this regular expression.
	// See: https://tailwindcss.com/docs/controlling-file-size/#understanding-the-regex
	defaultExtractor: content => content.match(/[\w-/.:]+(?<!:)/g) || [],
	// Whitelist auto generated classes for transitions and router links.
	// From: https://github.com/ky-is/vue-cli-plugin-tailwind
	whitelistPatterns: [/vue2leaflet-/,/leaflet-/,/-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^router-link(|-exact)-active$/],
});

module.exports = {
	"plugins": [
 		require('tailwindcss')('tailwind.js'),
 		require('autoprefixer')(),
		...process.env.NODE_ENV === 'production' ? [purgecss] : [],
	]
}
```
