### ISSUE TITLE
How use latLngBounds in Nuxt?

### ISSUE THREAD

**Issue by io777** [vue-leaflet/Vue2Leaflet#580]
How use latLngBounds in Nuxt? If` import { latLngBounds } from "leaflet";` in component. This good work in vue2, but not work in Nuxt. I have error on page - ReferenceError window is not defined. This is related to the server-side-rendered.

**Comment by DonNicoJs** [comment]
@io777 You to import `latLngBound` import inside `mounted` and use either `import()` or `require`
