### ISSUE TITLE
how to use multi marker props on single marker

### ISSUE THREAD

**Issue by mhmdkavosi** [vue-leaflet/Vue2Leaflet#582]
hi guys.
i need use rotationAngle(vue2-leaflet-rotatedmarker) and duration(vue2-leaflet-movingmarker)
but i want use two props in single marker.
for example :
```
<l-marker :lat-lng="run.currentPoint.latLong"
 :icon="run.currentPoint.icon" :rotationAngle="250" :duration="2000">
</l-marker>
```
thank you.

**Comment by DonNicoJs** [comment]
@mhmdkavosi I think this question is better asked on the plugins github, but feel free to hop on our DISCORD if you have more questions!
