### ISSUE TITLE
How to use interactive layer with GeoJson  

### ISSUE THREAD

**Issue by quanghuynguyen1902** [vue-leaflet/Vue2Leaflet#587]
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

I want to display geojson as example:  https://geojson-maps.ash.ms/

**Comment by DonNicoJs** [comment]
@quanghuynguyen1902 yuo can use `l-geo-json` for this! Please if you have more questions hop in on Discord, the link is in the README
