### ISSUE TITLE
L.vectorGrid.protobuf Feature

### ISSUE THREAD

**Issue by scirag** [vue-leaflet/Vue2Leaflet#594]
#### Live Demo

https://openmaptiles.org/docs/website/leaflet/

**Comment by DonNicoJs** [comment]
This sounds like a plugin request! Anyone interested please ping me here so I can create a base repo inside the org

**Comment by lostdesign** [comment]
I think the goal might be just vector maps in general? I just stumbled upon this [gist](https://gist.github.com/timwis/eb2c7824bc8dca1727bd1bd96ecf24f0) which explains how to use `Vue2Leaflet` with `mapbox-gl` / `mapbox-gl-leaflet`.

Maybe it's enough to update the docs on how to use `Vue2Leaflet` with Vector Maps? Perhaps even protobuf works the way described in the gist.
