### ISSUE TITLE
Add `draggable` option to LMap

### ISSUE THREAD

**Issue by mstephens** [vue-leaflet/Vue2Leaflet#595]
Hey, great project!

At the moment there is no property on `LMap` for `draggable`, is it possible to add this?

e.g.
```
  <LMap
    ref="map"
    :zoom="zoom"
    :center="center"
    :draggable="true"
  >
```

Thank you :]

**Comment by DonNicoJs** [comment]
@mstephens you can already configure `draggable` with the `options` prop, any prop that does not have a function inside `leaflet` that we can call to set/unset the value on the fly is routed through the `options` prop

`<l-map :options="{draggable: true}" ... />`
