### ISSUE TITLE
Symmetrically greyed-out outsides of round circles on the map

### ISSUE THREAD

**Issue by hvitis** [vue-leaflet/Vue2Leaflet#597]
### Description

Hello,

I've been looking a lot for an explanation or a solution. I am not sure it´s a bug or my incopetence but I am experiencing this:

<img width="651" alt="Screenshot 2020-06-27 at 14 51 42" src="https://user-images.githubusercontent.com/17104239/85922769-23902880-b886-11ea-99b7-1f6d241b915c.png">

Anybody knows why? Is it a bug?

That's inside a Buefy modal component. I´ve tried loading css, changing components, loading it in different places but get this all the time. Looks like some settings issue?

**Comment by DonNicoJs** [comment]
@hvitis this looks like a css bug can you check if your tiles have a border-radius applied? please hop on our discord to discuss this further if you don't manage to solve the issue!

**Comment by hvitis** [comment]
This was indeed a css problem. I had clip path applied... thank you for quick answer and sorry for bothering.
