### ISSUE TITLE
LGridLayer usage and props

### ISSUE THREAD

**Issue by empereira** [vue-leaflet/Vue2Leaflet#601]
hi,

Would it be possible to do the grid as shown below, with LGridLayer? Or do I need to use pure leaflet?

![image](https://user-images.githubusercontent.com/29874574/86859500-24e8fe80-c099-11ea-9984-4bedbbef8666.png)

**Comment by DonNicoJs** [comment]
@empereira You can use vue2-leaflet to mimic 99.99% of leaflet feature, so yes you can
