### ISSUE TITLE
wrong prop type in LPolyline > dashArray

### ISSUE THREAD

**Issue by comteharbour** [vue-leaflet/Vue2Leaflet#602]
### Description
Expected type is String. Working type is Array.

#### Steps to Reproduce
Add a LPolyline in LMap default slot with prop:
either `dashArray="[5, 10]"` (String)
either `:dashArray="[5, 10]"` (Array)

#### Expected Results
It displays a dashed polyline.
No error is throw

##### when dashArray prop is String "[5, 10]"
No error is throw.
Polyline is not dashed

##### when dashArray prop is String "[5, 10]"
Error is throw.
Polyline is dashed

### Browsers Affected

- [ x ] Chrome
- [ x ] Firefox
- [ ? ] Edge
- [ ? ] Safari 9
- [ ? ] Safari 8
- [ ? ] IE 11

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by DonNicoJs** [comment]
@comteharbour thank you for the report! Issue properly labeled

**Comment by comteharbour** [comment]
My bad. It works if we use the svg stroke-dasharray syntax.
`dashArray="5,10"
https://developer.mozilla.org/fr/docs/Web/SVG/Attribute/stroke-dasharray

It might be useful to add this link to documentation about components using dashArray (LCircle, LCircleMarker, LPolyline, Lpolygon, LRectangle). The name prompts to use an array, which works but throws an error.
