### ISSUE TITLE
[Question] - Put controls outside the map

### ISSUE THREAD

**Issue by byander** [vue-leaflet/Vue2Leaflet#603]
I would like to know if it's possible to put controls outside the map. 
For example, I have a component which contains a list of basemaps/overlayers and other component to render the map. 
It's possible interage between the components? 
Thank's
![example](https://user-images.githubusercontent.com/6788360/87553704-9fadad00-c689-11ea-891c-02c255b68b9a.JPG)

**Comment by DonNicoJs** [comment]
@byander Sure, you can put refs on the map and from then on use leaflet methods to mimic what control would do
