### ISSUE TITLE
Vue.js 3 compatibility

### ISSUE THREAD

**Issue by jdecool** [vue-leaflet/Vue2Leaflet#606]
Hi,

Vue.js 3 release is imminent and it seems that the component is not compatible yet.

Is it planned to release a version which compatible with the next release ?

**Comment by DonNicoJs** [comment]
@jdecool yep, we are working on a brand new version for vue 3 you can expect info soon!

**Comment by jdecool** [comment]
Great news !

Can't wait to test it.

**Comment by AbdullaevTimur** [comment]
Also waiting for)

**Comment by andi23rosca** [comment]
@DonNicoJs Was going to start a new project for a Vue3 compatible leaflet library but I think it's better if I contribute to an already existing one. Do you accept contributions at this stage for the new implementation?

**Comment by DonNicoJs** [comment]
@andi23rosca please let's not divide the efforts! I am working on the vue3 composition API based implementation here: https://github.com/vue-leaflet/vue-leaflet

I would like to have map, tilelayer and marker fully working and then using those as a base we can work on the rest, I am quite close to finish the 3 base ones you can take a peek at the code, then we can open issues for all the components and work them togheter, What do you think?

**Comment by andi23rosca** [comment]
@DonNicoJs Sounds good 👍

**Comment by jdecool** [comment]
@DonNicoJs The VueJS3 adaption looks promise !

Do you have news about an initial release ?

**Comment by DonNicoJs** [comment]
@jdecool We have an alpha released already: https://www.npmjs.com/package/@vue-leaflet/vue-leaflet
You can follow the development in the repo: https://github.com/vue-leaflet/vue-leaflet

**Comment by jdecool** [comment]
Thanks.

I'm going to test the new version :)
