### ISSUE TITLE
[Question] - How to render component inside marker

### ISSUE THREAD

**Issue by ThomasJRyan** [vue-leaflet/Vue2Leaflet#609]
Hello,

I am trying to render a third-party component inside of a marker. Specifically the `draggable` component from `VueDraggable`. I'm effectively trying to drop images onto a marker to update the icon and data (a bit more detailed than that, but using `VueDraggable` is essential for my needs). My first thought was to use a `divIcon`, but putting `<draggable/>` into it, but that causes it to literally add `<draggable/>` to the DOM instead of rendering the component.

At this point I'm fairly confident this isn't possible unless I'm missing something, so I guess this is also a feature request if at all possible. Thank you for any help you can provide!

**Comment by mikeu** [comment]
Hi @ThomasJRyan , I'm not sure what all you have or haven't tried, but my first stab would look something like this:
```
<l-marker ...>
  <l-icon ...>
    <third-party-component ... />
  </l-icon>
</l-marker>
```
That certainly works for getting some custom components into the icon slot, though I don't know for sure at this point how it'll interact with the drag-and-drop component you're working with. Another option might be to use a pop-up on the icon, and have your drop target in there.

If that doesn't resolve your issue, feel free to put together a minimal example as close to what you're trying to achieve as you can get on [codesandbox](https://codesandbox.io) or similar, and I'll see if I can figure out anything further from there.
