### ISSUE TITLE
How to init Vue2Leaflet map with the user current position set as center and latLng ?

### ISSUE THREAD

**Issue by faso-dev** [vue-leaflet/Vue2Leaflet#611]
Here's my map code

```vue
  <l-map
          @click="addMarker"
          :zoom="mapConfig.zoom"
          :center="askPermissionForCurrentPosition()"
      >
        <l-tile-layer
            :url="mapConfig.url"
            :attribution="mapConfig.attribution"
        />
        <l-marker
            :lat-lng="askPermissionForCurrentPosition()">
          <l-popup>
            <div>
              Votre position actuelle
            </div>
          </l-popup>
        </l-marker>
    </l-map>
```

My method to get user Position:
```js
askPermissionForCurrentPosition() {
      const vm = this
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(position => {
          vm.currentPosition = L.latLng(position.coords.latitude, position.coords.longitude)
        });
      } else {
        alert("Geolocation is not supported by this browser.");
      }
      return vm.currentPosition
    }
```
But i get this error, if some one can help me to fix it

`callback for watcher "latLng": "TypeError: Cannot read property 'lat' of null"

found in

---> <LMarker>
       <LMap>
         <Map> at src/components/Map.vue
           <VMain>
             <VApp>
               <App> at src/App.vue
                 <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
run @ vue.runtime.esm.js?2b0e:4570
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4631
eval @ Map.vue?108f:114
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'lat' of null
    at VueComponent.setLatLng (LMarker.js?4e2b:298)
    at VueComponent.vueElement.$watch.deep (LMarker.js?4e2b:39)
    at Watcher.run (vue.runtime.esm.js?2b0e:4568)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)
logError @ vue.runtime.esm.js?2b0e:1888
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
run @ vue.runtime.esm.js?2b0e:4570
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4631
eval @ Map.vue?108f:114
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "center": "Error: Set map center and zoom first."

found in

---> <LMap>
       <Map> at src/components/Map.vue
         <VMain>
           <VApp>
             <App> at src/App.vue
               <Root>`

**Comment by mikeu** [comment]
@faso-dev `vm.currentPosition` is null because your `askPermissionForCurrentPosition` finished executing before the callback to get the location is run after the user grants permission. You're better off setting the map `:center` and marker `lat-lng` to a (reactive) property on the component's `data` object, and updating that in the callback.

Here's an example: https://codesandbox.io/s/user-position-on-load-4dk1q?file=/src/components/Map.vue
