### ISSUE TITLE
Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined

### ISSUE THREAD

**Issue by alexey2baranov** [vue-leaflet/Vue2Leaflet#613]
I really don't know how to reproduce this bug. I hope it is as simple as you can investigate it looking on the stack trace below.

#### Steps to Reproduce
This bug appears when you resize browser window and quickly press "backward" browser's button to return to prev SPA page with map. You should press "backward" button very quick as fast as you can to reproduce this. I can suggest that it appears when map mounted during window resizing. VueLeaflet try to handle resize event and crashes with error. It is very hard to create JSFiddle for this situation for with my skills but i think you find this issue usefull. 

#### Investigation
After some investigation I set up conditional breakpoint with `!el` condition inside `Map#getPosition` and find that the `Map._mapPane===null`. This is incorrect state if you want to call `Map.getPosition()`. So I make suggestion `LMap.moveEndHandler` need to have additional check to prevent `Map.getPosition()` call when `Map._mapPane` is null. Hope this can be usefull.

```js
function getPosition(el) {
	// this method is only used for elements previously positioned using setPosition,
	// so it's safe to cache the position for performance

	return el._leaflet_pos || new Point(0, 0);   // <- code crashes hire. el (which is Map._mapPane) === null hire
} 
```

> VM1609:1 Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined
> getPosition (leaflet-src.js?e11e:2471)
> _getMapPanePos (leaflet-src.js?e11e:4488)
> containerPointToLayerPoint (leaflet-src.js?e11e:4062)
> _getCenterLayerPoint (leaflet-src.js?e11e:4525)
> getCenter (leaflet-src.js?e11e:3850)
> moveEndHandler (LMap.js?2699:436)
> (anonymous) (LMap.js?2699:15)
> setTimeout (async)
> eval (LMap.js?2699:14)
> fire (leaflet-src.js?e11e:593)
> setTimeout (async)
> invalidateSize (leaflet-src.js?e11e:3616)
> eval (leaflet-src.js?e11e:4354)
> requestAnimationFrame (async)
> requestAnimFrame (leaflet-src.js?e11e:244)
> _onResize (leaflet-src.js?e11e:4353)
> handler (leaflet-src.js?e11e:2679)

### Browsers Affected
- [ *] Chrome

### Versions
- Leaflet: v1.6.0
- Vue: v2.6.11
- Vue2Leaflet: v2.5.2

**Comment by mikeu** [comment]
Thanks for the issue, @alexey2baranov . I can confirm that I have been able to reproduce this manually in Chrome with some quick clicking of the back arrow. Haven't managed to come up with an approach that generates this error in a test, or reliably and automatically in a demo either, but will investigate it further!

**Comment by alexey2baranov** [comment]
@mikeu suddenly it breaks all my tests of one component with map. But it works good in other two components with vue-leaflet. It is very unpredictable when this error appears https://imgur.com/5EZ8xPv.png

**Comment by mikeu** [comment]
@alexey2baranov thanks for the update, that might be a useful step forward in debugging, if you have a test failing because of this error. Do you have an idea of how many times the test fails vs succeeds? Does the test also involve navigating quickly away from the page, or is this a different way to reproduce the error? Is there any difference you can identify between the failing component and the passing ones that might be related to the source of the problem?

Ideally, if you think you might be able to create a [codesandbox demo](https://codesandbox.io) (or similar) that fails reliably, hopefully without requiring any user intervention to trigger the error, that could really help to narrow down the issue.

**Comment by edwh** [comment]
I see this 10-20 times a day on a live site.  The site uses Sentry, so I get console logs running up to the error.  If there's any debug console logging which it would be useful to have, then I would be happy to install a test build on that site and collect diagnostics.

**Comment by alexey2baranov** [comment]
@mikeu unfortunately i can,t reproduce it in a separate test. My tests are too complex. Anyway If it helps i can share github link on them.

Peace of additional info: I found that tests throw this error when i add router and routing into vue component. So if i test parent component, which contains vueleaflet, then everything is fine. But if i add a vue router into parent and  make some router.push(some route) , then this error throws. Looks like router.push()  similates UI backspase from the first comment of this issue.

**Comment by ctot-nondef** [comment]
I can reproduce this in a nuxt setup upon every navigation away from a map view. 

the stack trace tells me (similar to the original post) that something triggers the getCenter function through the maps moveEndHandler, oddly when the map component is actually destroyed. other than clogging the logs/console it doesn't do much damage but it ain't pretty.

```
leaflet-src.js?e11e:2450 Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined
    at getPosition (leaflet-src.js?e11e:2450)
    at NewClass._getMapPanePos (leaflet-src.js?e11e:4439)
    at NewClass.containerPointToLayerPoint (leaflet-src.js?e11e:4013)
    at NewClass._getCenterLayerPoint (leaflet-src.js?e11e:4476)
    at NewClass.getCenter (leaflet-src.js?e11e:3801)
    at VueComponent.moveEndHandler (LMap.js?2699:436)
    at eval (LMap.js?2699:15)
```
