### ISSUE TITLE
`token` prop for LTileLayer problem

### ISSUE THREAD

**Issue by ala747** [vue-leaflet/Vue2Leaflet#620]
Hi! I may be missing something but I can't get `<l-tile-layer>` working with Mapbox because the `token` prop doesn't seem to be there anymore:

![image](https://user-images.githubusercontent.com/162955/91213932-a280d080-e712-11ea-989e-3df50efcdc68.png)

I did a quick look in the src code here but didn't find the prop nowhere (beside the examples). Does Vue2leaflet not support the `token` prop anymore or it might be set other way?

Thanks in advance!

**Comment by mikeu** [comment]
Hi @ala747 ! Thanks for pointing this out, it looks as if the docs indeed don't match the code in this case. The issue likely arises from the fact that `accessToken` is an undocumented Leaflet option that appears to have been contributing to documentation issues for two years now: https://github.com/Leaflet/Leaflet/issues/6336.

However, you should still be able to use this undocumented option through vue2-leaflet:
```vue
<l-tile-layer :options="{ accessToken: 'your.mapbox.access.token' } ... />
```

Does that work for you?

**Comment by ala747** [comment]
Hi @mikeu ! You are The Man, it actually works like a charm! 😃 

I were digging on previous tags and PRs and did found an old `params` prop which used to work like your `options` but unfortunately it doesn't work either.

Thank you very much for this wrapper and your help, you saved my week!
