### ISSUE TITLE
get error after build the project and introduce vue2-leaflet.min.js 

### ISSUE THREAD

**Issue by edgexie** [vue-leaflet/Vue2Leaflet#630]
### Description
steps
1. git clone the project
2. npm i
3. npm run build
4. create a index.html in dist/ 
```
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<script src="./vue2-leaflet.min.js"></script>
	<script type="text/javascript">
	</script>
</head>
<body>

</body>
</html>
```
5. node http-server in dist
6. get error
`vue2-leaflet.min.js:2 Uncaught SyntaxError: Invalid or unexpected token`

I think this error from rollup's setting~
How can i deal with it?

### env
- windows10

**Comment by mikeu** [comment]
Hi @edgexie , thanks for the issue report. Are you still having problems with this?

I'm having trouble reproducing the issue myself. I followed the steps you provided on Windows 10 in a regular command prompt, a cmder.net shell, and in Ubuntu under WSL just as a check. All three compile the project and serve the `dist/index.html` file without error (other than not finding the favicon the browser asks for).

There are some warnings during the build in the Windows command prompts that aren't present under WSL, which look like this for many of the components:
```
./src/components/LImageOverlay.vue → dist/components/LImageOverlay.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
D:PathToRepos♂2l-630
untimeplugin-vue
ormalize.js (imported by src\components\LImageOverlay.vue)
created dist/components/LImageOverlay.js in 51ms
```
but as you can see, the component is still created in `dist`.

When I `cd dist && http-server`, I get this output:
```
Starting up http-server, serving ./
Available on:
  http://192.168.0.107:8080
  http://127.0.0.1:8080
  http://172.20.0.1:8080
Hit CTRL-C to stop the server
```
and visiting 127.0.0.1:8080 in my browser gives me a blank page with no errors (again, other than no favicon).

Do you have any suggestions for changes to the rollup config that might resolve the problem you're seeing?

**Comment by edgexie** [comment]
@mikeu hi !  thanks for your reply.  My buiding js like the picture here~ Anything wrong?
![image](https://user-images.githubusercontent.com/18474752/93831876-8ab35280-fca6-11ea-9d42-7488f1de1ff1.png)

**Comment by mikeu** [comment]
@edgexie yeah, there are definitely some issues in there. Those entries that look like `'D:webVue2Leaflet'` for example, shouldn't be there, and should have actually imported the functions from files starting with `D:\web\Vue2Leaflet\...`. It looks as if something in rollup isn't handling the Windows backslash directory separator correctly...

OK, it seems to be [this issue in rollup-plugin-vue 5.1.2-4](https://github.com/vuejs/rollup-plugin-vue/issues/303). You should be able to resolve it by installing either 5.1.1, or 5.1.5+.
