### ISSUE TITLE
2 Markers don't shortest path

### ISSUE THREAD

**Issue by Pakinwet** [vue-leaflet/Vue2Leaflet#635]
### Description

I put marker pins to Japan and USA but result is around the world. I don't know why not directly Japan to USA?

#### Expected Results

<img width="510" alt="Screen Shot 2563-10-07 at 13 50 50" src="https://user-images.githubusercontent.com/9396436/95298632-9312ac80-08a6-11eb-9381-43f929066aa5.png">

### Browsers Affected

- [x] Chrome

### Versions
- Leaflet: ^1.7.1
- Vue: ^2.6.11
- Vue2Leaflet: ^2.5.2

**Comment by mikeu** [comment]
Hi @Pakinwet , thanks for the feedback! Have you built the same map in Leaflet (without Vue2Leaflet), and seen different behaviour? I haven't worked much with trying to make maps cross the antimeridian, but my first thought is that this is how the underlying Leaflet map works by default.

If you put together a [sample application](https://codesandbox.io/s/vue2-leaflet-boilerplate-b47h9) showing what you've tried, we might be able to provide a little more help. For example, what longitude did you provide for USA? What wrapping settings have you chosen for the map and the CRS? What logic did you put in to try to display the shortest distance between your two points?

**Comment by Pakinwet** [comment]
Thanks a lot for your fast help.
For now I solved my issue with handle longitudes outside the [-180..180] range.
Ref: https://stackoverflow.com/questions/40532496/wrapping-lines-polygons-across-the-antimeridian-in-leaflet-js
