### ISSUE TITLE
Update the package in npm

### ISSUE THREAD

**Issue by samdzone** [vue-leaflet/Vue2Leaflet#636]
### Description

Update the package in npm

The example shows the absence disableScrollPropagation in LControl

#### Live Demo

https://codesandbox.io/s/young-architecture-qrrqr?file=/App.vue

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by mikeu** [comment]
@DonNicoJs This is probably a good idea before too long, we've had several PRs merged since the last release. What do you think, want to take care of that?

**Comment by DonNicoJs** [comment]
@samdzone  @mikeu thanks for the ping! new version updateD: https://www.npmjs.com/package/vue2-leaflet

**Comment by samdzone** [comment]
Thank you for efficiency
