### ISSUE TITLE
can you add chinese translate for this map

### ISSUE THREAD

**Issue by martinwithyou** [vue-leaflet/Vue2Leaflet#637]
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by mikeu** [comment]
Hi @martinwithyou , I am not sure whether you mean the map data, or the map controls.

If you mean the map controls, then you can use any existing [Leaflet](https://leafletjs.com/reference-1.7.1.html) options for that. For example, here is a map with custom tooltip titles on the zoom in and out buttons: https://jsfiddle.net/munderwood/5kuva6f8/9/ (forgive the translations, I used a computer translator and have no idea how accurate they are!).

But if you mean the actual map data, then this project has no affiliation with OpenStreetMap (or any other map data source), so you will have to find another source with the translations that you want, or look into helping to translate the existing OSM data (see e.g. their [translation](https://wiki.openstreetmap.org/wiki/Translation) and [name localization](https://wiki.openstreetmap.org/wiki/Names#Localization) pages).

**Comment by martinwithyou** [comment]
ok，我不确定您指的是地图数据还是地图控件。

如果您指的是地图控件，那么您可以使用任何现有的宣传单选项。例如，这里有一张地图，放大和缩小按钮上都有自定义的工具提示标题：https://jsfiddle.net/munderwood/5kuva6f8/9/(恕我直言，我用的是计算机翻译器，我不知道它们有多准确！)。

但是，如果您指的是实际的地图数据，则此项目与OpenStreetMap(或任何其他地图数据源)没有任何从属关系，因此您必须找到具有您想要的翻译的另一个来源，或者考虑帮助翻译现有的OSM数据(例如，请参阅其翻译和名称本地化页面)。

**Comment by mikeu** [comment]
As far as I can tell that is simply the translation of my previous comment, now available here for future reference :)

**Comment by martinwithyou** [comment]
> As far as I can tell that is simply the translation of my previous comment, now available here for future reference :)

thank you, 谢谢你。。。爱你哦。。。
