### ISSUE TITLE
Vue2Leaflet "broken" documentation

### ISSUE THREAD

**Issue by Gaspadlo** [vue-leaflet/Vue2Leaflet#639]
Hey guys, once you figure out a fix for the docs loading async components, could you share your solution/findings afterwards, please? 😂 

We've had the very same kind of error (couple of weeks ago) suddenly pop up out of nowhere for some of our components in our product and for the love of god, we could not figure out what has started causing it. A "cowardly" hotfix at the time was just making those problematic components synchronous...

Well - cheers and good luck!

> [Vue warn]: Failed to resolve async component: function Layout() {
>     return __webpack_require__.e(/*! import() */ 1).then(__webpack_require__.bind(null, /*! ./node_modules/@vuepress/theme-default/layouts/Layout.vue */ "./node_modules/@vuepress/theme-default/layouts/Layout.vue"));
>   }

(Our hunch has been, that some chained dependency probably raised a minor version of some module, that somehow broke / introduced an edge-case split chunking bug and in case that hunch is correct - then that's "looking a for a needle in a haystack")

![image](https://user-images.githubusercontent.com/4014669/96161783-0310da80-0f18-11eb-8042-f2ef1e44f6fd.png)

**Comment by DonNicoJs** [comment]
@Gaspadlo Fixed! an `npm update` on our module did the trick! Apparently the `npm audit --fix` did introduce some incompatibility between our deps! Thank you for opening this
