### ISSUE TITLE
small Typo in props

### ISSUE THREAD

**Issue by elmatou** [vue-leaflet/Vue2Leaflet#646]
https://github.com/vue-leaflet/Vue2Leaflet/blob/3efc8f4b698ae380167d660a41141ab39bcf6820/src/components/LMarker.vue#L40

should be `custom` and not `custon`

**Comment by mikeu** [comment]
Nice catch @elmatou , thanks for the report! Luckily it won't have made much difference, since `opacity.custom` is still falsy when undefined, but might as well have it correct :)
