### ISSUE TITLE
Sending auth headers

### ISSUE THREAD

**Issue by MortezaMohiuodin** [vue-leaflet/Vue2Leaflet#652]
Hello, How can I send auth headers for tiles? I searched in docs but I found no options.

**Comment by mikeu** [comment]
Hi @MortezaMohiuodin , thanks for the question!

I don't believe that Leaflet supports that functionality natively, does it? I found a rather old issue about it that more recently mentions the possibility of plugins or custom class extensions, but unless it is a core feature of Leaflet itself, then it is likely better to write a plugin for Vue2Leaflet than to try to add it to the core library here.

Maybe something in that discussion at Leaflet/Leaflet#2091 will be helpful. Please do let us know if there is a Leaflet option or method that Vue2Leaflet is missing, though!
