### ISSUE TITLE
LCircleMarker - using prop "lStyle" throws a deprecation warning in the console

### ISSUE THREAD

**Issue by udos** [vue-leaflet/Vue2Leaflet#653]
awesome library! thanks!

I had to use **_LCircleMarker_** and was surprised to find that there is a prop **_lStyle_** (which I have not encounterd so far, I'm used to find **_options-style_**)

- https://vue2-leaflet.netlify.app/components/LCircleMarker.html#props

using prop **_lStyle_** throws this deprecation warning in the console:
```console
LCircleMarker.js:312 lStyle is deprecated and is going to be removed in the next major version
```

### Versions
- Leaflet: v1.7.1
- Vue: v2.6.10
- Vue2Leaflet: v2.5.2

**Comment by mikeu** [comment]
Thanks, @udos ! Indeed I don't believe there are any plans to include `lStyle` as a prop in the next release of [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet). I'm not sure what issue you are reporting here though, are you saying you'd prefer not to be warned in the console that the option will be deprecated, if you do choose to use it in this version?

**Comment by udos** [comment]
apologies :| I think I have completly misunderstood the available options of LCircleMarker. instead of using them directly, e.g. like `color` in 
`<l-circle-marker
      :lat-lng="circle.center"
      :radius="circle.radius"
      :color="circle.color"
    />`
I was looking for a prop `options-style` which is not available in [CircleMarker](https://leafletjs.com/reference-1.7.1.html#circlemarker)

my bad. sorry about this. I close the "issue".
