### ISSUE TITLE
Using Plugin leaflet-measure

### ISSUE THREAD

**Issue by gmdMETIS** [vue-leaflet/Vue2Leaflet#655]
Hello, I'm trying to integrate https://github.com/ljagis/leaflet-measure, but the instruction are for a classic installation of Leaflet, and in the documentation of Vue2Leaflet I don't find any indication of how to use normal plugins. Can you help me?

**Comment by mikeu** [comment]
Hi @gmdMETIS , if you only need to measure distances, then you might simply be able to use the [vue2-leaflet-polyline-measure](https://github.com/mikeu/vue2-leaflet-polyline-measure) plugin that already exists. But if you do require leaflet-measure, then please try taking a look at how the polyline-measure plugin is structured; it shouldn't be too hard to create a similar wrapper for other vanilla Leaflet plugins.

If you end up publishing a Vue2Leaflet wrapper for the plugin, let us know and we will add it to the documentation here!
