### ISSUE TITLE
Error using map inside a component that extends Mixin

### ISSUE THREAD

**Issue by lucabecchetti** [vue-leaflet/Vue2Leaflet#660]
I have a component that extend Mixin from external library, and I got this error:

```
marker-field:50039 TypeError: Cannot read property 'addLayer' of null
    at VueComponent.mounted (marker-field:69199)
    at invokeWithErrorHandling (marker-field:50005)
```

If I remove Mix and use extend Vue, works, any idea? Thanks!

**Comment by mikeu** [comment]
Hi @lucabecchetti , something like this is going to be very difficult to debug if we don't know what the component looks like, which mixin it extends, which external library it is referencing, how that relates to Vue2Leaflet, or when during execution the error occurs.

Are you able to provide a minimal working example on e.g. codesandbox or jsfiddle, demoing the error?
