### ISSUE TITLE
No release notes for any version after v2.4.3

### ISSUE THREAD

**Issue by unikitty37** [vue-leaflet/Vue2Leaflet#663]
### Description

When viewing the releases list at https://github.com/vue-leaflet/Vue2Leaflet/releases, it shows this as the latest version despite the current version being v2.6.0: 

v2.4.3 - Marker visible prop fix

There is a rather unobvious "show 4 newer tags" above it, but this doesn't actually produce any release notes whatsoever. There is no CHANGELOG.md, either.

Please could we have *some* form of release notes for each release, just so we know it's not likely to break anything when we upgrade? Having to paw through all the commits to find out what they do is not really a substitute…

#### Live Demo

n/a

#### Steps to Reproduce

Go to https://github.com/vue-leaflet/Vue2Leaflet/releases

#### Expected Results

Each version shows the changes made in that version, even if the log is something along the lines of "version bump to fix packaging problem".

#### Actual Results

I have no idea whether I am about to install something which will change the way my code interacts with it.

### Browsers Affected

n/a

### Versions

- Leaflet: v1.7.1
- Vue: v2.6.12
- Vue2Leaflet: v2.6.0

**Comment by DonNicoJs** [comment]
@unikitty37 We did not do any major release since v2, we simply apply bug fixes, is true we should be more diligent with release notes, but we are short staffed and IRL is eating us alive :) Any help is very welcome
