### ISSUE TITLE
How to listen layer's change?

### ISSUE THREAD

**Issue by trdmm** [vue-leaflet/Vue2Leaflet#688]
When I use **LControlLayers**,how can i listen layer's change?

_I am a noob ._

I want to use 2 map: A and B. A contains one img tile, B contains 2 tile: img tile and annotation tile.
So, I want to use **LControlLayers** and **LTileLayer** to set A&B img tile layer,and listen layer's change to show B's annotation tile. But  **LControlLayers** has only one event: ready. 😭 

Or,Is there any other better way?

**Comment by mikeu** [comment]
Hi @trdmm, the controls in Vue2Leaflet also allow you to listen to every event emitted by the underlying [Leaflet components](https://leafletjs.com/reference-1.7.1.html). In this case, what you'll want is to listen for the [`baselayerchange`](https://leafletjs.com/reference-1.7.1.html#map-baselayerchange) event from the map, something like this:
```vue
<l-map @baselayerchange="layerChanged" ...>
  <l-control-layers />
  <l-tile-layer layer-type="base" .../>
  <l-tile-layer layer-type="base" .../>
</l-map>
```

**Comment by xlcrr** [comment]
```javascript

var layerControls = L.control.layers(null, overlays);

map.on('overlayadd', changeLayers);
map.on('overlayremove', changeLayers);

function changeLayers (layer) 
{
    ...
}
```

**Comment by trdmm** [comment]
> Hi @trdmm, the controls in Vue2Leaflet also allow you to listen to every event emitted by the underlying [Leaflet components](https://leafletjs.com/reference-1.7.1.html). In this case, what you'll want is to listen for the [`baselayerchange`](https://leafletjs.com/reference-1.7.1.html#map-baselayerchange) event from the map, something like this:
> 
> ```
> <l-map @baselayerchange="layerChanged" ...>
>   <l-control-layers />
>   <l-tile-layer layer-type="base" .../>
>   <l-tile-layer layer-type="base" .../>
> </l-map>
> ```

Thanks 👍

**Comment by trdmm** [comment]
> ```js
> var layerControls = L.control.layers(null, overlays);
> 
> map.on('overlayadd', changeLayers);
> map.on('overlayremove', changeLayers);
> 
> function changeLayers (layer) 
> {
>     ...
> }
> ```

Thanks good idea. 😺
