### ISSUE TITLE
More prominent reminder about OpenStreetMap required attribution

### ISSUE THREAD

**Issue by cquest** [vue-leaflet/Vue2Leaflet#690]
### Description
Missing attribution in "Quickstart" + more visibility to attribution requirements for OpenStreetMap

#### Live Demo

https://vue2-leaflet.netlify.app/quickstart/

#### Expected Results
OpenStreetMap attribution is often missing. All examples in the documentation are correct except this one and also on https://vue2-leaflet.netlify.app/components/LTileLayer.html

It will also be better to have some reminder clearly mentionning that attribution is required when OpenStreetMap basemaps are used, like it is clearly mentionned in the Leaflet documentation.

A link to https://openstreetmap.org/copyright would be really appreciated to make things clear for the vu2-leaflet component users event if the component can be used with other basemaps (which must be in a minor number of cases).

Thanks in advance.

#### Actual Results
Missing attribution on map.

### Browsers Affected

All

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by mikeu** [comment]
Hi @cquest, thank you for reporting this, that is absolutely an important point!

**Comment by cquest** [comment]
Thanks a lot !
