### ISSUE TITLE
Cannot add alt-text to l-marker icon

### ISSUE THREAD

**Issue by bche1132** [vue-leaflet/Vue2Leaflet#699]
### Description
Cannot add alt-text to l-marker icon. Have not seen this in the docs. This is an attribute in leaflet itself, but have seen no props or way to pass in alt-text with the vue-leaflet package

#### Live Demo
http://jsfiddle.net/2qcgwLm7/
Inspect icon with your browser, no alternate text is available, even though the markers are part of the tab index. 

#### Steps to Reproduce
N/A

#### Expected Results
alternate text is available 

#### Actual Results
alt is blank

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 9
- [X] Safari 8
- [X] IE 11

### Versions
- Leaflet: v1.7.1
- Vue: v2.6.12
- Vue2Leaflet: v2.6.0

**Comment by mikeu** [comment]
Hi @bche1132 , you should be able to pass any Leaflet option that does not have a corresponding Vue prop via the `options` object prop. For example,
```vue
<l-marker :lat-lng="marker" :options="{alt: 'default marker'}"></l-marker>
```

Does that work for you?

**Comment by bche1132** [comment]
@mikeu yes! Thank you that's perfect. 
Appreciate the quick response!
