### ISSUE TITLE
popups broke

### ISSUE THREAD

**Issue by Enhed** [vue-leaflet/Vue2Leaflet#712]
The latest version does not work with openPopup. For example, the example from the documentation https://vue2-leaflet.netlify.app/components/LFeatureGroup.html#demo does not work on the new project

**Comment by janiskelemen** [comment]
+1

**Comment by mikeu** [comment]
Thanks for reporting this issue! Are you able to provide any more context, or a reproduction of the issue?

Here is the example from the docs working with the latest version: https://codesandbox.io/s/v2l-popups-working-ln3bgt?file=/src/App.vue
